$(document).ready(function() {
  var units = [
    {id: 0, stars: "**", text: "Fencer Vargas", cost: "2,500", materials: ["Fire Nymph"]},
    {id: 1, stars: "***", text: "Burning Vargas", cost: "100,000", materials: ["Fire Spirit", "Fire Idol"]},
    {id: 2, stars: "****", text: "Fire King Vargas", cost: "200,000", materials: ["Fire Nymph", "Fire Nymph", "Fire Spirit", "Fire Idol", "Fire Totem"]},
    {id: 3, stars: "*****", text: "Fire God Vargas", cost: "500,000", materials: ["Fire Nymph", "Fire Spirit", "Fire Idol", "Fire Totem", "Miracle Totem"]},
    {id: 4, stars: "******", text: "Holy Flame Vargas", cost: "", materials: []},
    {id: 5, stars: "**", text: "Beast Zegar", cost: "50,000", materials: ["Fire Nymph", "Fire Nymph", "Fire Spirit"]},
    {id: 6, stars: "***", text: "Rage Beast Zegar", cost: "100,000", materials: ["Fire Nymph", "Fire Nymph", "Fire Spirit", "Fire Idol"]},
    {id: 7, stars: "****", text: "Fire Beast Zegar", cost: "200,000", materials: ["Fire Nymph", "Fire Idol", "Fire Idol", "Fire Totem", "Fire Pot"]},
    {id: 8, stars: "*****", text: "Beast King Zegar", cost: "", materials: []},
    {id: 9, stars: "*", text: "Burny", cost: "1,000", materials: ["Fire Nymph"]},
    {id: 10, stars: "**", text: "King Burny", cost: "", materials: []},
    {id: 11, stars: "*", text: "Witch Liza", cost: "5,000", materials: ["Fire Nymph"]},
    {id: 12, stars: "**", text: "Warlock Liza", cost: "50,000", materials: ["Fire Nymph", "Fire Spirit"]},
    {id: 13, stars: "***", text: "Pyromancer Liza", cost: "", materials: []},
    {id: 14, stars: "*", text: "Goblin", cost: "2,500", materials: ["Mimic"]},
    {id: 15, stars: "**", text: "Redcap", cost: "", materials: []},
    {id: 16, stars: "**", text: "Thief Leon", cost: "50,000", materials: ["Fire Nymph", "Fire Nymph", "Fire Spirit"]},
    {id: 17, stars: "***", text: "Head Thief Leon", cost: "100,000", materials: ["Fire Nymph", "Fire Idol", "Mimic", "Mimic"]},
    {id: 18, stars: "****", text: "Great Thief Leon", cost: "", materials: []},
    {id: 19, stars: "**", text: "Orthos", cost: "50,000", materials: ["Fire Nymph", "Mimic", "Mimic"]},
    {id: 20, stars: "***", text: "Cerberus", cost: "", materials: []},
    {id: 21, stars: "**", text: "Salamander", cost: "50,000", materials: ["Fire Nymph", "Fire Spirit", "Mimic"]},
    {id: 22, stars: "***", text: "Ifrit", cost: "100,000", materials: ["Fire Spirit", "Fire Nymph", "Mimic"]},
    {id: 23, stars: "****", text: "Malvan", cost: "", materials: []},
    {id: 24, stars: "***", text: "Firedrake", cost: "100,000", materials: ["Fire Spirit", "Fire Spirit", "Fire Spirit", "Bat Mimic"]},
    {id: 25, stars: "****", text: "Dragon Graven", cost: "200,000", materials: ["Fire Totem", "Fire Idol", "Fire Spirit", "Fire Nymph", "Bat Mimic"]},
    {id: 26, stars: "*****", text: "Dalimaone", cost: "", materials: []},
    {id: 27, stars: "***", text: "Knight Agni", cost: "100,000", materials: ["Fire Spirit", "Fire Idol", "Bat Mimic"]},
    {id: 28, stars: "****", text: "Fire Knight Agni", cost: "200,000", materials: ["Fire Nymph", "Fire Nymph", "Fire Idol", "Fire Totem", "Fire Pot"]},
    {id: 29, stars: "*****", text: "Magma Knight Agni", cost: "", materials: []},
    {id: 30, stars: "***", text: "Phoenix", cost: "100,000", materials: ["Fire Idol", "Bat Mimic"]},
    {id: 31, stars: "****", text: "Lava Phoenix", cost: "200,000", materials: ["Fire Nymph", "Fire Spirit", "Fire Totem", "Mimic", "Bat Mimic"]},
    {id: 32, stars: "*****", text: "God Phoenix", cost: "500,000", materials: ["Fire Nymph", "Fire Spirit", "Fire Totem", "Miracle Totem", "Dragon Mimic"]},
    {id: 33, stars: "******", text: "Phoenix Reborn", cost: "", materials: []},
    {id: 34, stars: "***", text: "Lava", cost: "100,000", materials: ["Fire Spirit", "Fire Spirit", "Fire Spirit", "Fire Idol"]},
    {id: 35, stars: "****", text: "Fire Knight Lava", cost: "200,000", materials: ["Fire Nymph", "Fire Nymph", "Fire Idol", "Fire Totem", "Bat Mimic"]},
    {id: 36, stars: "*****", text: "Fire God Lava", cost: "500,000", materials: ["Miracle Totem", "Fire Totem", "Dragon Mimic", "Fire Idol", "Fire Pot"]},
    {id: 37, stars: "******", text: "Sacred Flame Lava", cost: "", materials: []},
    {id: 38, stars: "**", text: "Blacksmith Galant", cost: "50,000", materials: ["Fire Nymph", "Fire Nymph", "Fire Nymph", "Fire Spirit", "Mimic"]},
    {id: 39, stars: "***", text: "Bruiser Galant", cost: "100,000", materials: ["Fire Nymph", "Fire Nymph", "Fire Spirit", "Fire Idol", "Bat Mimic"]},
    {id: 40, stars: "****", text: "God Arm Galant", cost: "200,000", materials: ["Fire Nymph", "Fire Spirit", "Fire Totem", "Fire Pot", "Bat Mimic"]},
    {id: 41, stars: "*****", text: "Smith Lord Galant", cost: "", materials: []},
    {id: 42, stars: "***", text: "Lancia", cost: "100,000", materials: ["Fire Nymph", "Fire Nymph", "Fire Idol", "Mimic"]},
    {id: 43, stars: "****", text: "Hot Chef Lancia", cost: "200,000", materials: ["Fire Nymph", "Fire Idol", "Fire Totem", "Mimic", "Bat Mimic"]},
    {id: 44, stars: "*****", text: "Head Chef Lancia", cost: "", materials: []},
    {id: 45, stars: "***", text: "Lorand", cost: "100,000", materials: ["Fire Nymph", "Fire Nymph", "Fire Nymph", "Fire Idol"]},
    {id: 46, stars: "****", text: "Professor Lorand", cost: "200,000", materials: ["Fire Idol", "Fire Idol", "Fire Totem", "Bat Mimic", "Bat Mimic"]},
    {id: 47, stars: "*****", text: "Master Lorand", cost: "", materials: []},
    {id: 48, stars: "**", text: "Orc", cost: "50,000", materials: ["Fire Spirit", "Mimic"]},
    {id: 49, stars: "***", text: "Ogre", cost: "", materials: []},
    {id: 50, stars: "**", text: "Hermit Talos", cost: "50,000", materials: ["Fire Nymph", "Fire Spirit"]},
    {id: 51, stars: "***", text: "Mountaineer Talos", cost: "", materials: []},
    {id: 52, stars: "***", text: "Fire Ghost", cost: "1,000", materials: ["Water Ghost", "Earth Ghost", "Thunder Ghost", "Light Ghost", "Metal Ghost"]},
    {id: 53, stars: "****", text: "Fire King", cost: "", materials: []},
    {id: 54, stars: "***", text: "Drake Chief Aisha", cost: "100,000", materials: ["Fire Nymph", "Fire Spirit", "Fire Spirit", "Fire Idol"]},
    {id: 55, stars: "****", text: "Drake Lord Aisha", cost: "200,000", materials: ["Fire Idol", "Fire Idol", "Fire Totem", "Bat Mimic", "Bat Mimic"]},
    {id: 56, stars: "*****", text: "Drake Queen Aisha", cost: "", materials: []},
    {id: 57, stars: "****", text: "Swordswoman Seria", cost: "200,000", materials: ["Fire Idol", "Fire Idol", "Fire Totem", "Fire Pot", "Fire Pot"]},
    {id: 58, stars: "*****", text: "Blade God Seria", cost: "", materials: []},
    {id: 59, stars: "****", text: "Freya", cost: "200,000", materials: ["Fire Totem", "Fire Idol", "Fire Spirit", "Fire Pot", "Light Pot"]},
    {id: 60, stars: "*****", text: "Blaze Sibyl Freya", cost: "", materials: []},
    {id: 61, stars: "****", text: "Red Axe Michele", cost: "200,000", materials: ["Fire Idol", "Fire Idol", "Fire Totem", "Fire Pot", "Bat Mimic"]},
    {id: 62, stars: "*****", text: "Lotus Axe Michele", cost: "", materials: []},
    {id: 63, stars: "****", text: "War Demon Vishra", cost: "200,000", materials: ["Fire Nymph", "Fire Spirit", "Fire Idol", "Fire Totem", "Fire Pot"]},
    {id: 64, stars: "*****", text: "Rakshasa Vishra", cost: "", materials: []},
    {id: 65, stars: "***", text: "Maiden Cayena", cost: "100,000", materials: ["Fire Spirit", "Fire Spirit", "Fire Idol", "Fire Idol", "Mimic"]},
    {id: 66, stars: "****", text: "Hot Rocket Cayena", cost: "200,000", materials: ["Fire Spirit", "Fire Idol", "Fire Idol", "Fire Totem", "Bat Mimic"]},
    {id: 67, stars: "*****", text: "War Rocket Cayena", cost: "", materials: []},
    {id: 68, stars: "**", text: "Selena", cost: "2,500", materials: ["Water Nymph"]},
    {id: 69, stars: "***", text: "Ice Selena", cost: "100,000", materials: ["Water Spirit", "Water Idol"]},
    {id: 70, stars: "****", text: "Ice Queen Selena", cost: "200,000", materials: ["Water Nymph", "Water Nymph", "Water Spirit", "Water Idol", "Water Totem"]},
    {id: 71, stars: "*****", text: "Ice Goddess Selena", cost: "500,000", materials: ["Water Nymph", "Water Spirit", "Water Idol", "Water Totem", "Miracle Totem"]},
    {id: 72, stars: "******", text: "Holy Ice Selena", cost: "", materials: []},
    {id: 73, stars: "**", text: "Zephu", cost: "50,000", materials: ["Water Nymph", "Water Nymph", "Water Spirit"]},
    {id: 74, stars: "***", text: "Knight Zephu", cost: "100,000", materials: ["Water Nymph", "Water Nymph", "Water Spirit", "Water Idol"]},
    {id: 75, stars: "****", text: "Dragoon Zephu", cost: "200,000", materials: ["Water Nymph", "Water Idol", "Water Idol", "Water Totem", "Water Pot"]},
    {id: 76, stars: "*****", text: "Dragon Hero Zephu", cost: "", materials: []},
    {id: 77, stars: "*", text: "Squirty", cost: "1,000", materials: ["Water Nymph"]},
    {id: 78, stars: "**", text: "King Squirty", cost: "", materials: []},
    {id: 79, stars: "*", text: "Priest Merith", cost: "5,000", materials: ["Water Nymph"]},
    {id: 80, stars: "**", text: "Healer Merith", cost: "50,000", materials: ["Water Nymph", "Water Spirit"]},
    {id: 81, stars: "***", text: "Bishop Merith", cost: "", materials: []},
    {id: 82, stars: "*", text: "Merman", cost: "2,500", materials: ["Mimic"]},
    {id: 83, stars: "**", text: "Sahuagin", cost: "", materials: []},
    {id: 84, stars: "**", text: "Pirate Verica", cost: "50,000", materials: ["Water Nymph", "Water Nymph", "Water Spirit"]},
    {id: 85, stars: "***", text: "Plunderer Verica", cost: "100,000", materials: ["Water Nymph", "Water Idol", "Mimic", "Mimic"]},
    {id: 86, stars: "****", text: "Sea Prince Verica", cost: "", materials: []},
    {id: 87, stars: "**", text: "Ramia", cost: "50,000", materials: ["Water Nymph", "Mimic", "Mimic"]},
    {id: 88, stars: "***", text: "Scylla", cost: "", materials: []},
    {id: 89, stars: "**", text: "Rantoul", cost: "50,000", materials: ["Water Nymph", "Water Spirit", "Mimic"]},
    {id: 90, stars: "***", text: "Legtos", cost: "100,000", materials: ["Water Idol", "Water Spirit", "Water Spirit", "Mimic"]},
    {id: 91, stars: "****", text: "Legnaura", cost: "", materials: []},
    {id: 92, stars: "***", text: "Undine", cost: "100,000", materials: ["Water Spirit", "Water Spirit", "Water Spirit", "Bat Mimic"]},
    {id: 93, stars: "****", text: "Siren", cost: "200,000", materials: ["Water Totem", "Water Idol", "Water Spirit", "Water Nymph", "Bat Mimic"]},
    {id: 94, stars: "*****", text: "Meltia", cost: "", materials: []},
    {id: 95, stars: "***", text: "Knight Sergio", cost: "100,000", materials: ["Water Spirit", "Water Idol", "Bat Mimic"]},
    {id: 96, stars: "****", text: "Ice Ruler Sergio", cost: "200,000", materials: ["Water Nymph", "Water Nymph", "Water Idol", "Water Totem", "Water Pot"]},
    {id: 97, stars: "*****", text: "Ice Knight Sergio", cost: "", materials: []},
    {id: 98, stars: "***", text: "Leviathan", cost: "100,000", materials: ["Water Idol", "Bat Mimic"]},
    {id: 99, stars: "****", text: "Loch Ness", cost: "200,000", materials: ["Water Nymph", "Water Spirit", "Water Totem", "Mimic", "Bat Mimic"]},
    {id: 100, stars: "*****", text: "Malnaplis", cost: "500,000", materials: ["Water Nymph", "Water Spirit", "Water Totem", "Miracle Totem", "Dragon Mimic"]},
    {id: 101, stars: "******", text: "Felneus", cost: "", materials: []},
    {id: 102, stars: "***", text: "Captain Mega", cost: "100,000", materials: ["Water Spirit", "Water Spirit", "Water Spirit", "Water Idol"]},
    {id: 103, stars: "****", text: "War Captain Mega", cost: "200,000", materials: ["Water Nymph", "Water Nymph", "Water Idol", "Water Totem", "Bat Mimic"]},
    {id: 104, stars: "*****", text: "Commander Mega", cost: "500,000", materials: ["Water Idol", "Water Totem", "Water Pot", "Miracle Totem", "Dragon Mimic"]},
    {id: 105, stars: "******", text: "Sea King Mega", cost: "", materials: []},
    {id: 106, stars: "**", text: "Stya", cost: "50,000", materials: ["Water Nymph", "Water Nymph", "Water Nymph", "Water Spirit", "Mimic"]},
    {id: 107, stars: "***", text: "Snow Blade Stya", cost: "100,000", materials: ["Water Nymph", "Water Nymph", "Water Spirit", "Water Idol", "Bat Mimic"]},
    {id: 108, stars: "****", text: "Frost Queen Stya", cost: "200,000", materials: ["Water Nymph", "Water Spirit", "Water Totem", "Water Pot", "Bat Mimic"]},
    {id: 109, stars: "*****", text: "Mother Snow Stya", cost: "", materials: []},
    {id: 110, stars: "***", text: "Elimo", cost: "100,000", materials: ["Water Nymph", "Water Nymph", "Water Idol", "Mimic"]},
    {id: 111, stars: "****", text: "Royal Elimo", cost: "200,000", materials: ["Water Nymph", "Water Idol", "Water Totem", "Mimic", "Bat Mimic"]},
    {id: 112, stars: "*****", text: "Genius Elimo", cost: "", materials: []},
    {id: 113, stars: "***", text: "Dean", cost: "100,000", materials: ["Water Nymph", "Water Nymph", "Water Nymph", "Water Idol"]},
    {id: 114, stars: "****", text: "Ice Mage Dean", cost: "200,000", materials: ["Water Idol", "Water Idol", "Water Totem", "Bat Mimic", "Bat Mimic"]},
    {id: 115, stars: "*****", text: "Ice Wizard Dean", cost: "", materials: []},
    {id: 116, stars: "**", text: "Wendigo", cost: "50,000", materials: ["Water Spirit", "Mimic"]},
    {id: 117, stars: "***", text: "Hrungnir", cost: "", materials: []},
    {id: 118, stars: "**", text: "Black Rose Elize", cost: "50,000", materials: ["Water Nymph", "Water Spirit"]},
    {id: 119, stars: "***", text: "Frozen Rose Elize", cost: "", materials: []},
    {id: 120, stars: "***", text: "Water Ghost", cost: "1,000", materials: ["Fire Ghost", "Earth Ghost", "Thunder Ghost", "Light Ghost", "Metal Ghost"]},
    {id: 121, stars: "****", text: "Water King", cost: "", materials: []},
    {id: 122, stars: "***", text: "Twin Gem Rickel", cost: "100,000", materials: ["Water Nymph", "Water Spirit", "Water Spirit", "Water Idol"]},
    {id: 123, stars: "****", text: "Twin Flash Rickel", cost: "200,000", materials: ["Water Idol", "Water Idol", "Water Totem", "Bat Mimic", "Bat Mimic"]},
    {id: 124, stars: "*****", text: "Twin Shot Rickel", cost: "", materials: []},
    {id: 125, stars: "****", text: "Brave Knight Karl", cost: "200,000", materials: ["Water Idol", "Water Idol", "Water Totem", "Water Pot", "Water Pot"]},
    {id: 126, stars: "*****", text: "Ice Warrior Karl", cost: "", materials: []},
    {id: 127, stars: "****", text: "Eliza", cost: "200,000", materials: ["Water Totem", "Water Idol", "Water Spirit", "Water Pot", "Dark Pot"]},
    {id: 128, stars: "*****", text: "Snow Sibyl Eliza", cost: "", materials: []},
    {id: 129, stars: "****", text: "Polar Angel Tiara", cost: "200,000", materials: ["Water Idol", "Water Idol", "Water Totem", "Water Pot", "Bat Mimic"]},
    {id: 130, stars: "*****", text: "Ice Apostle Tiara", cost: "", materials: []},
    {id: 131, stars: "****", text: "Hail Bot Reeze", cost: "200,000", materials: ["Water Nymph", "Water Spirit", "Water Idol", "Water Totem", "Water Pot"]},
    {id: 132, stars: "*****", text: "Hail Mech Reeze", cost: "", materials: []},
    {id: 133, stars: "***", text: "Maiden Serin", cost: "100,000", materials: ["Water Spirit", "Water Spirit", "Water Idol", "Water Idol", "Mimic"]},
    {id: 134, stars: "****", text: "Gun Lady Serin", cost: "200,000", materials: ["Water Spirit", "Water Idol", "Water Idol", "Water Totem", "Bat Mimic"]},
    {id: 135, stars: "*****", text: "Gun Goddess Serin", cost: "", materials: []},
    {id: 136, stars: "**", text: "Pikeman Lance", cost: "2,500", materials: ["Earth Nymph"]},
    {id: 137, stars: "***", text: "Vine Pike Lance", cost: "100,000", materials: ["Earth Spirit", "Earth Idol"]},
    {id: 138, stars: "****", text: "Earth Pike Lance", cost: "200,000", materials: ["Earth Nymph", "Earth Nymph", "Earth Spirit", "Earth Idol", "Earth Totem"]},
    {id: 139, stars: "*****", text: "Nature God Lance", cost: "500,000", materials: ["Earth Nymph", "Earth Spirit", "Earth Idol", "Earth Totem", "Miracle Totem"]},
    {id: 140, stars: "******", text: "Holy Earth Lance", cost: "", materials: []},
    {id: 141, stars: "**", text: "Archer Lario", cost: "50,000", materials: ["Earth Nymph", "Earth Nymph", "Earth Spirit"]},
    {id: 142, stars: "***", text: "Marksman Lario", cost: "100,000", materials: ["Earth Nymph", "Earth Nymph", "Earth Spirit", "Earth Idol"]},
    {id: 143, stars: "****", text: "Hawkeye Lario", cost: "200,000", materials: ["Earth Nymph", "Earth Idol", "Earth Idol", "Earth Totem", "Earth Pot"]},
    {id: 144, stars: "*****", text: "Bow God Lario", cost: "", materials: []},
    {id: 145, stars: "*", text: "Mossy", cost: "1,000", materials: ["Earth Nymph"]},
    {id: 146, stars: "**", text: "King Mossy", cost: "", materials: []},
    {id: 147, stars: "*", text: "Geomancer Claris", cost: "5,000", materials: ["Earth Nymph"]},
    {id: 148, stars: "**", text: "Time Mage Claris", cost: "50,000", materials: ["Earth Nymph", "Earth Spirit"]},
    {id: 149, stars: "***", text: "Time Lord Claris", cost: "", materials: []},
    {id: 150, stars: "*", text: "Mandragora", cost: "2,500", materials: ["Mimic"]},
    {id: 151, stars: "**", text: "Polevik", cost: "", materials: []},
    {id: 152, stars: "**", text: "Bandit Zaza", cost: "50,000", materials: ["Earth Nymph", "Earth Nymph", "Earth Spirit"]},
    {id: 153, stars: "***", text: "Head Bandit Zaza", cost: "100,000", materials: ["Earth Nymph", "Earth Idol", "Mimic", "Mimic"]},
    {id: 154, stars: "****", text: "Wild Bandit Zaza", cost: "", materials: []},
    {id: 155, stars: "**", text: "Fairy", cost: "50,000", materials: ["Earth Nymph", "Mimic", "Mimic"]},
    {id: 156, stars: "***", text: "Titania", cost: "", materials: []},
    {id: 157, stars: "**", text: "Trent", cost: "50,000", materials: ["Earth Nymph", "Earth Spirit", "Mimic"]},
    {id: 158, stars: "***", text: "Ent", cost: "100,000", materials: ["Earth Spirit", "Earth Nymph", "Mimic"]},
    {id: 159, stars: "****", text: "Xipe Totec", cost: "", materials: []},
    {id: 160, stars: "***", text: "Dryad", cost: "100,000", materials: ["Earth Spirit", "Earth Spirit", "Earth Spirit", "Bat Mimic"]},
    {id: 161, stars: "****", text: "High Elf", cost: "200,000", materials: ["Earth Nymph", "Earth Spirit", "Earth Idol", "Earth Totem", "Bat Mimic"]},
    {id: 162, stars: "*****", text: "Lemenara", cost: "", materials: []},
    {id: 163, stars: "***", text: "Princess Lidith", cost: "100,000", materials: ["Earth Spirit", "Earth Idol", "Bat Mimic"]},
    {id: 164, stars: "****", text: "Queen Lidith", cost: "200,000", materials: ["Earth Nymph", "Earth Nymph", "Earth Idol", "Earth Totem", "Earth Pot"]},
    {id: 165, stars: "*****", text: "Empress Lidith", cost: "", materials: []},
    {id: 166, stars: "***", text: "Great Tree Alneu", cost: "100,000", materials: ["Earth Idol", "Bat Mimic"]},
    {id: 167, stars: "****", text: "World Tree Altro", cost: "200,000", materials: ["Earth Nymph", "Earth Spirit", "Earth Totem", "Mimic", "Bat Mimic"]},
    {id: 168, stars: "*****", text: "God Tree Eltri", cost: "500,000", materials: ["Earth Nymph", "Earth Spirit", "Earth Totem", "Miracle Totem", "Dragon Mimic"]},
    {id: 169, stars: "******", text: "Alpha Tree Altri", cost: "", materials: []},
    {id: 170, stars: "***", text: "Gunner Douglas", cost: "100,000", materials: ["Earth Spirit", "Earth Spirit", "Earth Spirit", "Earth Idol"]},
    {id: 171, stars: "****", text: "Gun King Douglas", cost: "200,000", materials: ["Earth Nymph", "Earth Nymph", "Earth Idol", "Earth Totem", "Bat Mimic"]},
    {id: 172, stars: "*****", text: "Gun God Douglas", cost: "500,000", materials: ["Miracle Totem", "Earth Totem", "Earth Idol", "Earth Pot", "Dragon Mimic"]},
    {id: 173, stars: "******", text: "Holy Arms Douglas", cost: "", materials: []},
    {id: 174, stars: "**", text: "Boxer Nemia", cost: "50,000", materials: ["Earth Nymph", "Earth Nymph", "Earth Nymph", "Earth Spirit", "Mimic"]},
    {id: 175, stars: "***", text: "Brawler Nemia", cost: "100,000", materials: ["Earth Nymph", "Earth Spirit", "Earth Spirit", "Earth Idol", "Bat Mimic"]},
    {id: 176, stars: "****", text: "Gaia Fist Nemia", cost: "200,000", materials: ["Earth Nymph", "Earth Spirit", "Earth Totem", "Earth Pot", "Bat Mimic"]},
    {id: 177, stars: "*****", text: "Quake Fist Nemia", cost: "", materials: []},
    {id: 178, stars: "***", text: "Pixy Leore", cost: "100,000", materials: ["Earth Nymph", "Earth Nymph", "Earth Idol", "Mimic"]},
    {id: 179, stars: "****", text: "Pixy Royal Leore", cost: "200,000", materials: ["Earth Nymph", "Earth Idol", "Earth Totem", "Mimic", "Bat Mimic"]},
    {id: 180, stars: "*****", text: "Pixy King Leore", cost: "", materials: []},
    {id: 181, stars: "***", text: "Edea", cost: "100,000", materials: ["Earth Nymph", "Earth Nymph", "Earth Spirit", "Earth Idol"]},
    {id: 182, stars: "****", text: "Earth Knight Edea", cost: "200,000", materials: ["Earth Idol", "Earth Idol", "Earth Totem", "Bat Mimic", "Bat Mimic"]},
    {id: 183, stars: "*****", text: "Mother Earth Edea", cost: "", materials: []},
    {id: 184, stars: "**", text: "Dwarf", cost: "50,000", materials: ["Earth Spirit", "Mimic"]},
    {id: 185, stars: "***", text: "Prince Dwarf", cost: "", materials: []},
    {id: 186, stars: "**", text: "Poet Elton", cost: "50,000", materials: ["Earth Nymph", "Earth Spirit"]},
    {id: 187, stars: "***", text: "Bard Elton", cost: "", materials: []},
    {id: 188, stars: "***", text: "Earth Ghost", cost: "1,000", materials: ["Fire Ghost", "Water Ghost", "Thunder Ghost", "Light Ghost", "Metal Ghost"]},
    {id: 189, stars: "****", text: "Earth King", cost: "", materials: []},
    {id: 190, stars: "***", text: "Twins Il &amp; Mina", cost: "100,000", materials: ["Earth Nymph", "Earth Spirit", "Earth Spirit", "Earth Idol"]},
    {id: 191, stars: "****", text: "Earthly Il &amp; Mina", cost: "200,000", materials: ["Earth Idol", "Earth Idol", "Earth Totem", "Bat Mimic", "Bat Mimic"]},
    {id: 192, stars: "*****", text: "Gemini Il &amp; Mina", cost: "", materials: []},
    {id: 193, stars: "****", text: "Warrior Lugina", cost: "200,000", materials: ["Earth Idol", "Earth Idol", "Earth Totem", "Earth Pot", "Earth Pot"]},
    {id: 194, stars: "*****", text: "Gaia King Lugina", cost: "", materials: []},
    {id: 195, stars: "****", text: "Paula", cost: "200,000", materials: ["Earth Spirit", "Earth Idol", "Earth Totem", "Earth Pot", "Dark Pot"]},
    {id: 196, stars: "*****", text: "Rose Sibyl Paula", cost: "", materials: []},
    {id: 197, stars: "****", text: "Scar Blade Zelban", cost: "200,000", materials: ["Earth Idol", "Earth Idol", "Earth Totem", "Earth Pot", "Bat Mimic"]},
    {id: 198, stars: "*****", text: "Blade Hero Zelban", cost: "", materials: []},
    {id: 199, stars: "****", text: "Golem", cost: "200,000", materials: ["Earth Idol", "Earth Idol", "Earth Totem", "Earth Pot", "Earth Pot"]},
    {id: 200, stars: "*****", text: "Great Golem", cost: "", materials: []},
    {id: 201, stars: "****", text: "Pugilist Dilma", cost: "200,000", materials: ["Earth Totem", "Earth Idol", "Earth Pot", "Earth Spirit", "Earth Nymph"]},
    {id: 202, stars: "*****", text: "Champ Fist Dilma", cost: "", materials: []},
    {id: 203, stars: "***", text: "Maiden Bayley", cost: "100,000", materials: ["Earth Spirit", "Earth Spirit", "Earth Idol", "Earth Idol", "Mimic"]},
    {id: 204, stars: "****", text: "Nyan Slash Bayley", cost: "200,000", materials: ["Earth Spirit", "Earth Idol", "Earth Idol", "Earth Totem", "Bat Mimic"]},
    {id: 205, stars: "*****", text: "Wild Slash Bayley", cost: "", materials: []},
    {id: 206, stars: "**", text: "Warrior Eze", cost: "2,500", materials: ["Thunder Nymph"]},
    {id: 207, stars: "***", text: "Thunder Eze", cost: "100,000", materials: ["Thunder Spirit", "Thunder Idol"]},
    {id: 208, stars: "****", text: "Thunder King Eze", cost: "200,000", materials: ["Thunder Nymph", "Thunder Nymph", "Thunder Spirit", "Thunder Idol", "Thunder Totem"]},
    {id: 209, stars: "*****", text: "Thunder God Eze", cost: "500,000", materials: ["Thunder Nymph", "Thunder Spirit", "Thunder Idol", "Thunder Totem", "Miracle Totem"]},
    {id: 210, stars: "******", text: "Holy Thunder Eze", cost: "", materials: []},
    {id: 211, stars: "**", text: "Advisor Weiss", cost: "50,000", materials: ["Thunder Nymph", "Thunder Nymph", "Thunder Spirit"]},
    {id: 212, stars: "***", text: "Strategist Weiss", cost: "100,000", materials: ["Thunder Nymph", "Thunder Nymph", "Thunder Spirit", "Thunder Idol"]},
    {id: 213, stars: "****", text: "Commander Weiss", cost: "200,000", materials: ["Thunder Nymph", "Thunder Idol", "Thunder Idol", "Thunder Totem", "Thunder Pot"]},
    {id: 214, stars: "*****", text: "General Weiss", cost: "", materials: []},
    {id: 215, stars: "*", text: "Sparky", cost: "1,000", materials: ["Thunder Nymph"]},
    {id: 216, stars: "**", text: "King Sparky", cost: "", materials: []},
    {id: 217, stars: "*", text: "Dancer May", cost: "5,000", materials: ["Thunder Nymph"]},
    {id: 218, stars: "**", text: "High Dancer May", cost: "50,000", materials: ["Thunder Nymph", "Thunder Spirit"]},
    {id: 219, stars: "***", text: "Royal Dancer May", cost: "", materials: []},
    {id: 220, stars: "*", text: "Harpy", cost: "2,500", materials: ["Mimic"]},
    {id: 221, stars: "**", text: "Aero", cost: "", materials: []},
    {id: 222, stars: "**", text: "Sky Pirate Grafl", cost: "50,000", materials: ["Thunder Nymph", "Thunder Nymph", "Thunder Spirit"]},
    {id: 223, stars: "***", text: "Sky Boss Grafl", cost: "100,000", materials: ["Thunder Nymph", "Thunder Idol", "Mimic", "Mimic"]},
    {id: 224, stars: "****", text: "Sky Emperor Grafl", cost: "", materials: []},
    {id: 225, stars: "**", text: "Minotaur", cost: "50,000", materials: ["Thunder Nymph", "Mimic", "Mimic"]},
    {id: 226, stars: "***", text: "Cyclops", cost: "", materials: []},
    {id: 227, stars: "**", text: "Sylph", cost: "50,000", materials: ["Thunder Nymph", "Thunder Spirit", "Mimic"]},
    {id: 228, stars: "***", text: "Djin", cost: "100,000", materials: ["Thunder Spirit", "Thunder Nymph", "Mimic"]},
    {id: 229, stars: "****", text: "Crow Tengu", cost: "", materials: []},
    {id: 230, stars: "***", text: "Thunderbird", cost: "100,000", materials: ["Thunder Spirit", "Thunder Spirit", "Thunder Spirit", "Bat Mimic"]},
    {id: 231, stars: "****", text: "Great Falcon Ziz", cost: "200,000", materials: ["Thunder Totem", "Thunder Idol", "Thunder Spirit", "Thunder Nymph", "Bat Mimic"]},
    {id: 232, stars: "*****", text: "Zazabis", cost: "", materials: []},
    {id: 233, stars: "***", text: "Sky Knight Falma", cost: "100,000", materials: ["Thunder Spirit", "Thunder Idol", "Bat Mimic"]},
    {id: 234, stars: "****", text: "Sky King Falma", cost: "200,000", materials: ["Thunder Nymph", "Thunder Nymph", "Thunder Idol", "Thunder Totem", "Thunder Pot"]},
    {id: 235, stars: "*****", text: "Sky Legend Falma", cost: "", materials: []},
    {id: 236, stars: "***", text: "Behemoth", cost: "100,000", materials: ["Thunder Idol", "Bat Mimic"]},
    {id: 237, stars: "****", text: "King Behemoth", cost: "200,000", materials: ["Thunder Nymph", "Thunder Spirit", "Thunder Totem", "Mimic", "Bat Mimic"]},
    {id: 238, stars: "*****", text: "Alpha Behemoth", cost: "500,000", materials: ["Thunder Nymph", "Thunder Spirit", "Thunder Totem", "Miracle Totem", "Dragon Mimic"]},
    {id: 239, stars: "******", text: "Omega Behemoth", cost: "", materials: []},
    {id: 240, stars: "***", text: "Emilia", cost: "100,000", materials: ["Thunder Spirit", "Thunder Spirit", "Thunder Spirit", "Thunder Idol"]},
    {id: 241, stars: "****", text: "Princess Emilia", cost: "200,000", materials: ["Thunder Nymph", "Thunder Nymph", "Thunder Idol", "Thunder Totem", "Bat Mimic"]},
    {id: 242, stars: "*****", text: "Goddess Emilia", cost: "500,000", materials: ["Thunder Idol", "Thunder Pot", "Thunder Totem", "Miracle Totem", "Dragon Mimic"]},
    {id: 243, stars: "******", text: "Holy Shock Emilia", cost: "", materials: []},
    {id: 244, stars: "**", text: "Zeln", cost: "50,000", materials: ["Thunder Nymph", "Thunder Nymph", "Thunder Nymph", "Thunder Spirit", "Mimic"]},
    {id: 245, stars: "***", text: "Spark Kick Zeln", cost: "100,000", materials: ["Thunder Nymph", "Thunder Nymph", "Thunder Spirit", "Thunder Idol", "Bat Mimic"]},
    {id: 246, stars: "****", text: "Thunder Kick Zeln", cost: "200,000", materials: ["Thunder Nymph", "Thunder Spirit", "Thunder Totem", "Thunder Pot", "Bat Mimic"]},
    {id: 247, stars: "*****", text: "Thunder Punt Zeln", cost: "", materials: []},
    {id: 248, stars: "***", text: "Tinkerer Elulu", cost: "100,000", materials: ["Thunder Nymph", "Thunder Nymph", "Thunder Idol", "Mimic"]},
    {id: 249, stars: "****", text: "Inventor Elulu", cost: "200,000", materials: ["Thunder Nymph", "Thunder Idol", "Thunder Totem", "Mimic", "Bat Mimic"]},
    {id: 250, stars: "*****", text: "Bolt Mallet Elulu", cost: "", materials: []},
    {id: 251, stars: "***", text: "Loch", cost: "100,000", materials: ["Thunder Nymph", "Thunder Nymph", "Thunder Spirit", "Thunder Idol"]},
    {id: 252, stars: "****", text: "Shock Bow Loch", cost: "200,000", materials: ["Thunder Idol", "Thunder Idol", "Thunder Totem", "Bat Mimic", "Bat Mimic"]},
    {id: 253, stars: "*****", text: "Zeus Bow Loch", cost: "", materials: []},
    {id: 254, stars: "**", text: "Empusa", cost: "50,000", materials: ["Thunder Spirit", "Mimic"]},
    {id: 255, stars: "***", text: "Gorgon", cost: "", materials: []},
    {id: 256, stars: "**", text: "Wild Cat Parmi", cost: "50,000", materials: ["Thunder Nymph", "Thunder Spirit"]},
    {id: 257, stars: "***", text: "Thunder Cat Parmi", cost: "", materials: []},
    {id: 258, stars: "***", text: "Thunder Ghost", cost: "1,000", materials: ["Fire Ghost", "Water Ghost", "Earth Ghost", "Light Ghost", "Metal Ghost"]},
    {id: 259, stars: "****", text: "Thunder King", cost: "", materials: []},
    {id: 260, stars: "***", text: "Bolt Pike Amy", cost: "100,000", materials: ["Thunder Nymph", "Thunder Spirit", "Thunder Spirit", "Thunder Idol"]},
    {id: 261, stars: "****", text: "Bolt Knight Amy", cost: "200,000", materials: ["Thunder Idol", "Thunder Idol", "Thunder Totem", "Bat Mimic", "Bat Mimic"]},
    {id: 262, stars: "*****", text: "Bolt Goddess Amy", cost: "", materials: []},
    {id: 263, stars: "****", text: "Paladin Paris", cost: "", materials: ["Thunder Totem", "Thunder Idol", "Thunder Idol", "TBA", "TBA"]},
    {id: 264, stars: "*****", text: "Royal Guard Paris", cost: "", materials: []},
    {id: 265, stars: "****", text: "Zele", cost: "200,000", materials: ["Thunder Totem", "Thunder Idol", "Thunder Spirit", "Thunder Pot", "Light Pot"]},
    {id: 266, stars: "*****", text: "Bolt Sibyl Zele", cost: "", materials: []},
    {id: 267, stars: "****", text: "Drakeborn Lodin", cost: "200,000", materials: ["Thunder Idol", "Thunder Idol", "Thunder Totem", "Thunder Pot", "Bat Mimic"]},
    {id: 268, stars: "*****", text: "Drake God Lodin", cost: "", materials: []},
    {id: 269, stars: "****", text: "Sky Angel Kushra", cost: "200,000", materials: ["Thunder Totem", "Thunder Idol", "Thunder Idol", "Thunder Pot", "Thunder Pot"]},
    {id: 270, stars: "*****", text: "Rebel Angel Elsel", cost: "", materials: []},
    {id: 271, stars: "****", text: "Shock Mage Rashil", cost: "200,000", materials: ["Thunder Nymph", "Thunder Spirit", "Thunder Idol", "Thunder Totem", "Thunder Pot"]},
    {id: 272, stars: "*****", text: "Bolt Magus Rashil", cost: "", materials: []},
    {id: 273, stars: "***", text: "Maiden Fennia", cost: "100,000", materials: ["Thunder Spirit", "Thunder Spirit", "Thunder Idol", "Thunder Idol", "Mimic"]},
    {id: 274, stars: "****", text: "Raid Bomb Fennia", cost: "200,000", materials: ["Thunder Spirit", "Thunder Idol", "Thunder Idol", "Thunder Totem", "Bat Mimic"]},
    {id: 275, stars: "*****", text: "Raid Bolt Fennia", cost: "", materials: []},
    {id: 276, stars: "**", text: "Squire Atro", cost: "50,000", materials: ["Light Nymph"]},
    {id: 277, stars: "***", text: "Knight Atro", cost: "100,000", materials: ["Light Spirit", "Light Idol"]},
    {id: 278, stars: "****", text: "Holy Knight Atro", cost: "200,000", materials: ["Light Nymph", "Light Nymph", "Light Spirit", "Light Idol", "Light Totem"]},
    {id: 279, stars: "*****", text: "God Atro", cost: "500,000", materials: ["Light Nymph", "Light Spirit", "Light Idol", "Light Totem", "Miracle Totem"]},
    {id: 280, stars: "******", text: "Holy Light Atro", cost: "", materials: []},
    {id: 281, stars: "**", text: "Luna", cost: "50,000", materials: ["Light Nymph", "Light Nymph", "Light Spirit"]},
    {id: 282, stars: "***", text: "Sunshine Luna", cost: "100,000", materials: ["Light Nymph", "Light Nymph", "Light Spirit", "Light Idol"]},
    {id: 283, stars: "****", text: "Holy Queen Luna", cost: "200,000", materials: ["Light Nymph", "Light Idol", "Light Idol", "Light Totem", "Light Pot"]},
    {id: 284, stars: "*****", text: "Holy Empress Luna", cost: "", materials: []},
    {id: 285, stars: "*", text: "Glowy", cost: "1,000", materials: ["Light Nymph"]},
    {id: 286, stars: "**", text: "King Glowy", cost: "", materials: []},
    {id: 287, stars: "*", text: "Sage Mimir", cost: "3,000", materials: ["Light Nymph"]},
    {id: 288, stars: "**", text: "Light Lord Mimir", cost: "50,000", materials: ["Light Nymph", "Light Spirit"]},
    {id: 289, stars: "***", text: "Great Sage Mimir", cost: "", materials: []},
    {id: 290, stars: "*", text: "Angel", cost: "5,000", materials: ["Mimic"]},
    {id: 291, stars: "**", text: "Archangel", cost: "", materials: []},
    {id: 292, stars: "**", text: "Unicorn", cost: "50,000", materials: ["Light Nymph", "Mimic", "Mimic"]},
    {id: 293, stars: "***", text: "Pegasus", cost: "", materials: []},
    {id: 294, stars: "**", text: "Priestess Maria", cost: "50,000", materials: ["Light Nymph", "Light Spirit", "Mimic"]},
    {id: 295, stars: "***", text: "Angel Maria", cost: "100,000", materials: ["Light Idol", "Light Spirit", "Light Nymph", "Mimic"]},
    {id: 296, stars: "****", text: "Saint Maria", cost: "", materials: []},
    {id: 297, stars: "***", text: "Valkyrie", cost: "100,000", materials: ["Light Spirit", "Light Spirit", "Light Spirit", "Bat Mimic"]},
    {id: 298, stars: "****", text: "Sky Hero Athena", cost: "200,000", materials: ["Light Totem", "Light Idol", "Light Spirit", "Light Nymph", "Bat Mimic"]},
    {id: 299, stars: "*****", text: "Legendary Jona", cost: "", materials: []},
    {id: 300, stars: "***", text: "Cowboy Heidt", cost: "100,000", materials: ["Light Spirit", "Light Idol", "Bat Mimic"]},
    {id: 301, stars: "****", text: "Holy Shot Heidt", cost: "200,000", materials: ["Light Nymph", "Light Nymph", "Light Idol", "Light Totem", "Light Pot"]},
    {id: 302, stars: "*****", text: "Pistol God Heidt", cost: "", materials: []},
    {id: 303, stars: "***", text: "Wyvern", cost: "100,000", materials: ["Light Idol", "Bat Mimic"]},
    {id: 304, stars: "****", text: "Bahamut", cost: "200,000", materials: ["Light Nymph", "Light Spirit", "Light Totem", "Mimic", "Bat Mimic"]},
    {id: 305, stars: "*****", text: "Rameldria", cost: "500,000", materials: ["Light Nymph", "Light Spirit", "Light Totem", "Miracle Totem", "Dragon Mimic"]},
    {id: 306, stars: "******", text: "Duelmex", cost: "", materials: []},
    {id: 307, stars: "***", text: "Knight Will", cost: "100,000", materials: ["Light Spirit", "Light Spirit", "Light Spirit", "Light Idol"]},
    {id: 308, stars: "****", text: "Holy Knight Will", cost: "200,000", materials: ["Light Nymph", "Light Nymph", "Light Idol", "Light Totem", "Bat Mimic"]},
    {id: 309, stars: "*****", text: "God Knight Will", cost: "500,000", materials: ["Light Idol", "Light Totem", "Dragon Mimic", "Light Pot", "Miracle Totem"]},
    {id: 310, stars: "******", text: "Holy Guard Will", cost: "", materials: []},
    {id: 311, stars: "**", text: "Traveler Alma", cost: "50,000", materials: ["Light Nymph", "Light Nymph", "Light Nymph", "Light Spirit", "Mimic"]},
    {id: 312, stars: "***", text: "Adventurer Alma", cost: "100,000", materials: ["Light Nymph", "Light Nymph", "Light Spirit", "Light Idol", "Bat Mimic"]},
    {id: 313, stars: "****", text: "Hero Alma", cost: "200,000", materials: ["Light Nymph", "Light Spirit", "Light Totem", "Light Pot", "Hero Alma"]},
    {id: 314, stars: "*****", text: "Brave Hero Alma", cost: "", materials: []},
    {id: 315, stars: "***", text: "Knight Aem", cost: "100,000", materials: ["Light Nymph", "Light Nymph", "Light Idol", "Mimic"]},
    {id: 316, stars: "****", text: "Champion Aem", cost: "200,000", materials: ["Light Nymph", "Light Idol", "Light Totem", "Mimic", "Bat Mimic"]},
    {id: 317, stars: "*****", text: "Holy Master Aem", cost: "", materials: []},
    {id: 318, stars: "***", text: "Eight Blade Sefia", cost: "100,000", materials: ["Light Nymph", "Light Spirit", "Light Spirit", "Light Idol"]},
    {id: 319, stars: "****", text: "Blade Storm Sefia", cost: "200,000", materials: ["Light Idol", "Light Idol", "Light Totem", "Bat Mimic", "Bat Mimic"]},
    {id: 320, stars: "*****", text: "Blade Queen Sefia", cost: "", materials: []},
    {id: 321, stars: "**", text: "Al-mi'raj", cost: "50,000", materials: ["Light Spirit", "Mimic"]},
    {id: 322, stars: "***", text: "Cait Sith", cost: "", materials: []},
    {id: 323, stars: "**", text: "Shrine Girl Amul", cost: "2,500", materials: ["Light Nymph", "Light Spirit"]},
    {id: 324, stars: "***", text: "Holy Maiden Amul", cost: "", materials: []},
    {id: 325, stars: "***", text: "Light Ghost", cost: "1,000", materials: ["Fire Ghost", "Water Ghost", "Earth Ghost", "Thunder Ghost", "Metal Ghost"]},
    {id: 326, stars: "****", text: "Light King", cost: "", materials: []},
    {id: 327, stars: "****", text: "Sola", cost: "200,000", materials: ["Light Totem", "Light Idol", "Light Spirit", "Fire Pot", "Thunder Pot"]},
    {id: 328, stars: "*****", text: "Ray Sibyl Sola", cost: "", materials: []},
    {id: 329, stars: "****", text: "Legionary Melchio", cost: "200,000", materials: ["Light Idol", "Light Idol", "Light Totem", "Light Pot", "Bat Mimic"]},
    {id: 330, stars: "*****", text: "Centurion Melchio", cost: "", materials: []},
    {id: 331, stars: "****", text: "White Lebra", cost: "200,000", materials: ["Light Totem", "Light Idol", "Light Idol", "Light Pot", "Light Pot"]},
    {id: 332, stars: "*****", text: "Lubradine", cost: "", materials: []},
    {id: 333, stars: "****", text: "Cyborg Lilith", cost: "200,000", materials: ["Light Nymph", "Light Spirit", "Light Idol", "Light Totem", "Light Pot"]},
    {id: 334, stars: "*****", text: "Cyborg Lilith II", cost: "", materials: []},
    {id: 335, stars: "***", text: "Maiden Vanila", cost: "100,000", materials: ["Light Spirit", "Light Spirit", "Light Idol", "Light Idol", "Mimic"]},
    {id: 336, stars: "****", text: "Sky Queen Vanila", cost: "200,000", materials: ["Light Spirit", "Light Idol", "Light Idol", "Light Totem", "Bat Mimic"]},
    {id: 337, stars: "*****", text: "Sky Angel Vanila", cost: "", materials: []},
    {id: 338, stars: "**", text: "Iron Magress", cost: "50,000", materials: ["Dark Nymph"]},
    {id: 339, stars: "***", text: "Heavy Magress", cost: "100,000", materials: ["Dark Spirit", "Dark Idol"]},
    {id: 340, stars: "****", text: "Black Magress", cost: "200,000", materials: ["Dark Nymph", "Dark Nymph", "Dark Spirit", "Dark Idol", "Dark Totem"]},
    {id: 341, stars: "*****", text: "Death Magress", cost: "500,000", materials: ["Dark Nymph", "Dark Spirit", "Dark Idol", "Dark Totem", "Miracle Totem"]},
    {id: 342, stars: "******", text: "Unholy Magress", cost: "", materials: []},
    {id: 343, stars: "**", text: "Mifune", cost: "50,000", materials: ["Dark Nymph", "Dark Nymph", "Dark Spirit"]},
    {id: 344, stars: "***", text: "Samurai Mifune", cost: "100,000", materials: ["Dark Nymph", "Dark Nymph", "Dark Spirit", "Dark Idol"]},
    {id: 345, stars: "****", text: "God Blade Mifune", cost: "200,000", materials: ["Dark Nymph", "Dark Idol", "Dark Idol", "Dark Totem", "Dark Pot"]},
    {id: 346, stars: "*****", text: "Ryujin Mifune", cost: "", materials: []},
    {id: 347, stars: "*", text: "Gloomy", cost: "1,000", materials: ["Dark Nymph"]},
    {id: 348, stars: "**", text: "King Gloomy", cost: "", materials: []},
    {id: 349, stars: "*", text: "Sorceress Lily", cost: "5,000", materials: ["Dark Nymph"]},
    {id: 350, stars: "**", text: "Magician Lily", cost: "50,000", materials: ["Dark Nymph", "Dark Spirit"]},
    {id: 351, stars: "***", text: "Dark Arts Lily", cost: "", materials: []},
    {id: 352, stars: "*", text: "Skeleton", cost: "2,500", materials: ["Mimic"]},
    {id: 353, stars: "**", text: "Skeleton King", cost: "", materials: []},
    {id: 354, stars: "**", text: "Medusa", cost: "50,000", materials: ["Dark Nymph", "Mimic", "Mimic"]},
    {id: 355, stars: "***", text: "Zahhak", cost: "", materials: []},
    {id: 356, stars: "**", text: "Lilin", cost: "50,000", materials: ["Dark Nymph", "Dark Spirit", "Mimic"]},
    {id: 357, stars: "***", text: "Succubus", cost: "100,000", materials: ["Dark Idol", "Dark Spirit", "Dark Nymph", "Mimic"]},
    {id: 358, stars: "****", text: "Nyx", cost: "", materials: []},
    {id: 359, stars: "***", text: "Vampire", cost: "100,000", materials: ["Dark Spirit", "Dark Spirit", "Dark Spirit", "Bat Mimic"]},
    {id: 360, stars: "****", text: "Lich", cost: "200,000", materials: ["Dark Totem", "Dark Idol", "Dark Spirit", "Dark Nymph", "Bat Mimic"]},
    {id: 361, stars: "*****", text: "Legion", cost: "", materials: []},
    {id: 362, stars: "***", text: "Shida", cost: "100,000", materials: ["Dark Spirit", "Dark Idol", "Bat Mimic"]},
    {id: 363, stars: "****", text: "Garroter Shida", cost: "200,000", materials: ["Dark Nymph", "Dark Nymph", "Dark Idol", "Dark Totem", "Dark Pot"]},
    {id: 364, stars: "*****", text: "Executioner Shida", cost: "", materials: []},
    {id: 365, stars: "***", text: "Memetes", cost: "100,000", materials: ["Dark Idol", "Bat Mimic"]},
    {id: 366, stars: "****", text: "Hell King Hades", cost: "200,000", materials: ["Dark Nymph", "Dark Spirit", "Dark Totem", "Mimic", "Bat Mimic"]},
    {id: 367, stars: "*****", text: "Death God Lodaga", cost: "500,000", materials: ["Dark Nymph", "Dark Spirit", "Dark Totem", "Miracle Totem", "Dragon Mimic"]},
    {id: 368, stars: "******", text: "Hellborn Dilias", cost: "", materials: []},
    {id: 369, stars: "***", text: "Alice", cost: "100,000", materials: ["Dark Spirit", "Dark Spirit", "Dark Spirit", "Dark Idol"]},
    {id: 370, stars: "****", text: "Scythe Alice", cost: "200,000", materials: ["Dark Nymph", "Dark Nymph", "Dark Idol", "Dark Totem", "Bat Mimic"]},
    {id: 371, stars: "*****", text: "Scythe God Alice", cost: "500,000", materials: ["Dark Pot", "Dark Idol", "Dragon Mimic", "Dark Totem", "Miracle Totem"]},
    {id: 372, stars: "******", text: "Hell Keep Alice", cost: "", materials: []},
    {id: 373, stars: "***", text: "Metal Ghost", cost: "1,000", materials: ["Water Ghost", "Fire Ghost", "Earth Ghost", "Thunder Ghost", "Light Ghost"]},
    {id: 374, stars: "****", text: "Metal King", cost: "", materials: []},
    {id: 375, stars: "**", text: "Ninja Oboro", cost: "50,000", materials: ["Dark Nymph", "Dark Nymph", "Dark Nymph", "Dark Spirit", "Mimic"]},
    {id: 376, stars: "***", text: "Assassin Oboro", cost: "100,000", materials: ["Dark Nymph", "Dark Nymph", "Dark Spirit", "Dark Idol", "Bat Mimic"]},
    {id: 377, stars: "****", text: "Shadow Oboro", cost: "200,000", materials: ["Dark Nymph", "Dark Spirit", "Dark Totem", "Dark Pot", "Bat Mimic"]},
    {id: 378, stars: "*****", text: "Red Shadow Oboro", cost: "", materials: []},
    {id: 379, stars: "***", text: "Lemia", cost: "100,000", materials: ["Dark Nymph", "Dark Nymph", "Dark Idol", "Mimic"]},
    {id: 380, stars: "****", text: "Necromancer Lemia", cost: "200,000", materials: ["Dark Nymph", "Dark Idol", "Dark Totem", "Mimic", "Bat Mimic"]},
    {id: 381, stars: "*****", text: "Soul Keeper Lemia", cost: "", materials: []},
    {id: 382, stars: "***", text: "Kikuri", cost: "100,000", materials: ["Dark Nymph", "Dark Spirit", "Dark Spirit", "Dark Idol"]},
    {id: 383, stars: "****", text: "Goth Kikuri", cost: "200,000", materials: ["Dark Spirit", "Dark Idol", "Dark Totem", "Bat Mimic", "Bat Mimic"]},
    {id: 384, stars: "*****", text: "Goth Idol Kikuri", cost: "", materials: []},
    {id: 385, stars: "**", text: "Imp", cost: "50,000", materials: ["Dark Spirit", "Mimic"]},
    {id: 386, stars: "***", text: "Incubus", cost: "", materials: []},
    {id: 387, stars: "**", text: "Gambler Zeul", cost: "50,000", materials: ["Dark Nymph", "Dark Spirit"]},
    {id: 388, stars: "***", text: "High Roller Zeul", cost: "", materials: []},
    {id: 389, stars: "****", text: "Disciple Zebra", cost: "200,000", materials: ["Dark Idol", "Dark Idol", "Dark Totem", "Dark Pot", "Dark Pot"]},
    {id: 390, stars: "*****", text: "Mad God Zebra", cost: "", materials: []},
    {id: 391, stars: "****", text: "Madia", cost: "200,000", materials: ["Dark Totem", "Dark Idol", "Dark Spirit", "Water Pot", "Earth Pot"]},
    {id: 392, stars: "*****", text: "Night Sibyl Madia", cost: "", materials: []},
    {id: 393, stars: "****", text: "Duel-GX", cost: "200,000", materials: ["Dark Idol", "Dark Idol", "Dark Totem", "Dark Pot", "Bat Mimic"]},
    {id: 394, stars: "*****", text: "Duel-GX II", cost: "", materials: []},
    {id: 395, stars: "****", text: "Dark Swords Logan", cost: "200,000", materials: ["Dark Nymph", "Dark Spirit", "Dark Idol", "Dark Totem", "Dark Pot"]},
    {id: 396, stars: "*****", text: "Evil Blades Logan", cost: "", materials: []},
    {id: 397, stars: "***", text: "Maiden Lico", cost: "100,000", materials: ["Dark Spirit", "Dark Spirit", "Dark Idol", "Dark Idol", "Mimic"]},
    {id: 398, stars: "****", text: "Dark Blade Lico", cost: "200,000", materials: ["Dark Idol", "Dark Idol", "Dark Totem", "Bat Mimic", "Bat Mimic"]},
    {id: 399, stars: "*****", text: "Demon Blade Lico", cost: "", materials: []},
    {id: 400, stars: "***", text: "Xenon", cost: "", materials: ["Dark Idol", "Dark Spirit", "Dark Nymph", "Dark Pot", "Mimic"]},
    {id: 401, stars: "****", text: "Royal Guard Xenon", cost: "", materials: []}
  ];

  var unitInventory = $.totalStorage('unitInventory') || [];
  var evoMats;

  render();

  $('#search-unit').select2({
    data: units
  }).on('change', function(selectedObject) {
    unitInventory.push(selectedObject.added);
    evoMats = [];
    evoMats.push(selectedObject.added.materials);

    $.totalStorage('unitInventory', unitInventory);
    // console.log(unitInventory);
    render();
  });

  function render() {
    tableBody = $('#unit-list tbody');
    tableBody.html('');

    $.each(unitInventory, function(index, unit) {
      tableRow = "<tr><td>" + unit.text + "</td><td>" + unit.cost + "</td><td>" + unit.materials + "</td></tr>";
      tableBody.append(tableRow);
    });

    renderTotalEvoMatCounts();
  }

  var totalEvoMats = {};

  function countEvoMats() {
    // flatten the array
    evoMats = [].concat.apply([], evoMats);

    for(i = 0; i < evoMats.length; ++i) {
      if(!totalEvoMats[evoMats[i]])
        totalEvoMats[evoMats[i]] = 0;
      ++totalEvoMats[evoMats[i]];
    }
  }

  function renderTotalEvoMatCounts() {
    countEvoMats();
    tableBody = $('#total-evo-counts tbody');
    tableBody.html('');

    for(key in totalEvoMats) {
      console.log(key);
      tableRow = "<tr><td>" + key + "</td><td>" + totalEvoMats[key] + "</td></tr>";
      tableBody.append(tableRow);
    }
  }
});
