$(document).ready(function() {
  var units = [
    {id: 0, stars: "**", text: "Fencer Vargas", materials: ["Fire Nymph"]},
    {id: 1, stars: "***", text: "Burning Vargas", materials: ["Fire Spirit", "Fire Idol"]},
    {id: 2, stars: "****", text: "Fire King Vargas", materials: ["Fire Nymph", "Fire Nymph", "Fire Spirit", "Fire Idol", "Fire Totem"]},
    {id: 3, stars: "*****", text: "Fire God Vargas", materials: ["Fire Nymph", "Fire Spirit", "Fire Idol", "Fire Totem", "Miracle Totem"]},
    {id: 4, stars: "******", text: "Holy Flame Vargas", materials: []},
    {id: 5, stars: "**", text: "Beast Zegar", materials: ["Fire Nymph", "Fire Nymph", "Fire Spirit"]},
    {id: 6, stars: "***", text: "Rage Beast Zegar", materials: ["Fire Nymph", "Fire Nymph", "Fire Spirit", "Fire Idol"]},
    {id: 7, stars: "****", text: "Fire Beast Zegar", materials: ["Fire Nymph", "Fire Idol", "Fire Idol", "Fire Totem", "Fire Pot"]},
    {id: 8, stars: "*****", text: "Beast King Zegar", materials: []},
    {id: 9, stars: "*", text: "Burny", materials: ["Fire Nymph"]},
    {id: 10, stars: "**", text: "King Burny", materials: []},
    {id: 11, stars: "*", text: "Witch Liza", materials: ["Fire Nymph"]},
    {id: 12, stars: "**", text: "Warlock Liza", materials: ["Fire Nymph", "Fire Spirit"]},
    {id: 13, stars: "***", text: "Pyromancer Liza", materials: []},
    {id: 14, stars: "*", text: "Goblin", materials: ["Mimic"]},
    {id: 15, stars: "**", text: "Redcap", materials: []},
    {id: 16, stars: "**", text: "Thief Leon", materials: ["Fire Nymph", "Fire Nymph", "Fire Spirit"]},
    {id: 17, stars: "***", text: "Head Thief Leon", materials: ["Fire Nymph", "Fire Idol", "Mimic", "Mimic"]},
    {id: 18, stars: "****", text: "Great Thief Leon", materials: []},
    {id: 19, stars: "**", text: "Orthos", materials: ["Fire Nymph", "Mimic", "Mimic"]},
    {id: 20, stars: "***", text: "Cerberus", materials: []},
    {id: 21, stars: "**", text: "Salamander", materials: ["Fire Nymph", "Fire Spirit", "Mimic"]},
    {id: 22, stars: "***", text: "Ifrit", materials: ["Fire Spirit", "Fire Nymph", "Mimic"]},
    {id: 23, stars: "****", text: "Malvan", materials: []},
    {id: 24, stars: "***", text: "Firedrake", materials: ["Fire Spirit", "Fire Spirit", "Fire Spirit", "Bat Mimic"]},
    {id: 25, stars: "****", text: "Dragon Graven", materials: ["Fire Totem", "Fire Idol", "Fire Spirit", "Fire Nymph", "Bat Mimic"]},
    {id: 26, stars: "*****", text: "Dalimaone", materials: []},
    {id: 27, stars: "***", text: "Knight Agni", materials: ["Fire Spirit", "Fire Idol", "Bat Mimic"]},
    {id: 28, stars: "****", text: "Fire Knight Agni", materials: ["Fire Nymph", "Fire Nymph", "Fire Idol", "Fire Totem", "Fire Pot"]},
    {id: 29, stars: "*****", text: "Magma Knight Agni", materials: []},
    {id: 30, stars: "***", text: "Phoenix", materials: ["Fire Idol", "Bat Mimic"]},
    {id: 31, stars: "****", text: "Lava Phoenix", materials: ["Fire Nymph", "Fire Spirit", "Fire Totem", "Mimic", "Bat Mimic"]},
    {id: 32, stars: "*****", text: "God Phoenix", materials: ["Fire Nymph", "Fire Spirit", "Fire Totem", "Miracle Totem", "Dragon Mimic"]},
    {id: 33, stars: "******", text: "Phoenix Reborn", materials: []},
    {id: 34, stars: "***", text: "Lava", materials: ["Fire Spirit", "Fire Spirit", "Fire Spirit", "Fire Idol"]},
    {id: 35, stars: "****", text: "Fire Knight Lava", materials: ["Fire Nymph", "Fire Nymph", "Fire Idol", "Fire Totem", "Bat Mimic"]},
    {id: 36, stars: "*****", text: "Fire God Lava", materials: ["Miracle Totem", "Fire Totem", "Dragon Mimic", "Fire Idol", "Fire Pot"]},
    {id: 37, stars: "******", text: "Sacred Flame Lava", materials: []},
    {id: 38, stars: "**", text: "Blacksmith Galant", materials: ["Fire Nymph", "Fire Nymph", "Fire Nymph", "Fire Spirit", "Mimic"]},
    {id: 39, stars: "***", text: "Bruiser Galant", materials: ["Fire Nymph", "Fire Nymph", "Fire Spirit", "Fire Idol", "Bat Mimic"]},
    {id: 40, stars: "****", text: "God Arm Galant", materials: ["Fire Nymph", "Fire Spirit", "Fire Totem", "Fire Pot", "Bat Mimic"]},
    {id: 41, stars: "*****", text: "Smith Lord Galant", materials: []},
    {id: 42, stars: "***", text: "Lancia", materials: ["Fire Nymph", "Fire Nymph", "Fire Idol", "Mimic"]},
    {id: 43, stars: "****", text: "Hot Chef Lancia", materials: ["Fire Nymph", "Fire Idol", "Fire Totem", "Mimic", "Bat Mimic"]},
    {id: 44, stars: "*****", text: "Head Chef Lancia", materials: []},
    {id: 45, stars: "***", text: "Lorand", materials: ["Fire Nymph", "Fire Nymph", "Fire Nymph", "Fire Idol"]},
    {id: 46, stars: "****", text: "Professor Lorand", materials: ["Fire Idol", "Fire Idol", "Fire Totem", "Bat Mimic", "Bat Mimic"]},
    {id: 47, stars: "*****", text: "Master Lorand", materials: []},
    {id: 48, stars: "**", text: "Orc", materials: ["Fire Spirit", "Mimic"]},
    {id: 49, stars: "***", text: "Ogre", materials: []},
    {id: 50, stars: "**", text: "Hermit Talos", materials: ["Fire Nymph", "Fire Spirit"]},
    {id: 51, stars: "***", text: "Mountaineer Talos", materials: []},
    {id: 52, stars: "***", text: "Fire Ghost", materials: ["Water Ghost", "Earth Ghost", "Thunder Ghost", "Light Ghost", "Metal Ghost"]},
    {id: 53, stars: "****", text: "Fire King", materials: []},
    {id: 54, stars: "***", text: "Drake Chief Aisha", materials: ["Fire Nymph", "Fire Spirit", "Fire Spirit", "Fire Idol"]},
    {id: 55, stars: "****", text: "Drake Lord Aisha", materials: ["Fire Idol", "Fire Idol", "Fire Totem", "Bat Mimic", "Bat Mimic"]},
    {id: 56, stars: "*****", text: "Drake Queen Aisha", materials: []},
    {id: 57, stars: "****", text: "Swordswoman Seria", materials: ["Fire Idol", "Fire Idol", "Fire Totem", "Fire Pot", "Fire Pot"]},
    {id: 58, stars: "*****", text: "Blade God Seria", materials: []},
    {id: 59, stars: "****", text: "Freya", materials: ["Fire Totem", "Fire Idol", "Fire Spirit", "Fire Pot", "Light Pot"]},
    {id: 60, stars: "*****", text: "Blaze Sibyl Freya", materials: []},
    {id: 61, stars: "****", text: "Red Axe Michele", materials: ["Fire Idol", "Fire Idol", "Fire Totem", "Fire Pot", "Bat Mimic"]},
    {id: 62, stars: "*****", text: "Lotus Axe Michele", materials: []},
    {id: 63, stars: "****", text: "War Demon Vishra", materials: ["Fire Nymph", "Fire Spirit", "Fire Idol", "Fire Totem", "Fire Pot"]},
    {id: 64, stars: "*****", text: "Rakshasa Vishra", materials: []},
    {id: 65, stars: "***", text: "Maiden Cayena", materials: ["Fire Spirit", "Fire Spirit", "Fire Idol", "Fire Idol", "Mimic"]},
    {id: 66, stars: "****", text: "Hot Rocket Cayena", materials: ["Fire Spirit", "Fire Idol", "Fire Idol", "Fire Totem", "Bat Mimic"]},
    {id: 67, stars: "*****", text: "War Rocket Cayena", materials: []},
    {id: 68, stars: "**", text: "Selena", materials: ["Water Nymph"]},
    {id: 69, stars: "***", text: "Ice Selena", materials: ["Water Spirit", "Water Idol"]},
    {id: 70, stars: "****", text: "Ice Queen Selena", materials: ["Water Nymph", "Water Nymph", "Water Spirit", "Water Idol", "Water Totem"]},
    {id: 71, stars: "*****", text: "Ice Goddess Selena", materials: ["Water Nymph", "Water Spirit", "Water Idol", "Water Totem", "Miracle Totem"]},
    {id: 72, stars: "******", text: "Holy Ice Selena", materials: []},
    {id: 73, stars: "**", text: "Zephu", materials: ["Water Nymph", "Water Nymph", "Water Spirit"]},
    {id: 74, stars: "***", text: "Knight Zephu", materials: ["Water Nymph", "Water Nymph", "Water Spirit", "Water Idol"]},
    {id: 75, stars: "****", text: "Dragoon Zephu", materials: ["Water Nymph", "Water Idol", "Water Idol", "Water Totem", "Water Pot"]},
    {id: 76, stars: "*****", text: "Dragon Hero Zephu", materials: []},
    {id: 77, stars: "*", text: "Squirty", materials: ["Water Nymph"]},
    {id: 78, stars: "**", text: "King Squirty", materials: []},
    {id: 79, stars: "*", text: "Priest Merith", materials: ["Water Nymph"]},
    {id: 80, stars: "**", text: "Healer Merith", materials: ["Water Nymph", "Water Spirit"]},
    {id: 81, stars: "***", text: "Bishop Merith", materials: []},
    {id: 82, stars: "*", text: "Merman", materials: ["Mimic"]},
    {id: 83, stars: "**", text: "Sahuagin", materials: []},
    {id: 84, stars: "**", text: "Pirate Verica", materials: ["Water Nymph", "Water Nymph", "Water Spirit"]},
    {id: 85, stars: "***", text: "Plunderer Verica", materials: ["Water Nymph", "Water Idol", "Mimic", "Mimic"]},
    {id: 86, stars: "****", text: "Sea Prince Verica", materials: []},
    {id: 87, stars: "**", text: "Ramia", materials: ["Water Nymph", "Mimic", "Mimic"]},
    {id: 88, stars: "***", text: "Scylla", materials: []},
    {id: 89, stars: "**", text: "Rantoul", materials: ["Water Nymph", "Water Spirit", "Mimic"]},
    {id: 90, stars: "***", text: "Legtos", materials: ["Water Idol", "Water Spirit", "Water Spirit", "Mimic"]},
    {id: 91, stars: "****", text: "Legnaura", materials: []},
    {id: 92, stars: "***", text: "Undine", materials: ["Water Spirit", "Water Spirit", "Water Spirit", "Bat Mimic"]},
    {id: 93, stars: "****", text: "Siren", materials: ["Water Totem", "Water Idol", "Water Spirit", "Water Nymph", "Bat Mimic"]},
    {id: 94, stars: "*****", text: "Meltia", materials: []},
    {id: 95, stars: "***", text: "Knight Sergio", materials: ["Water Spirit", "Water Idol", "Bat Mimic"]},
    {id: 96, stars: "****", text: "Ice Ruler Sergio", materials: ["Water Nymph", "Water Nymph", "Water Idol", "Water Totem", "Water Pot"]},
    {id: 97, stars: "*****", text: "Ice Knight Sergio", materials: []},
    {id: 98, stars: "***", text: "Leviathan", materials: ["Water Idol", "Bat Mimic"]},
    {id: 99, stars: "****", text: "Loch Ness", materials: ["Water Nymph", "Water Spirit", "Water Totem", "Mimic", "Bat Mimic"]},
    {id: 100, stars: "*****", text: "Malnaplis", materials: ["Water Nymph", "Water Spirit", "Water Totem", "Miracle Totem", "Dragon Mimic"]},
    {id: 101, stars: "******", text: "Felneus", materials: []},
    {id: 102, stars: "***", text: "Captain Mega", materials: ["Water Spirit", "Water Spirit", "Water Spirit", "Water Idol"]},
    {id: 103, stars: "****", text: "War Captain Mega", materials: ["Water Nymph", "Water Nymph", "Water Idol", "Water Totem", "Bat Mimic"]},
    {id: 104, stars: "*****", text: "Commander Mega", materials: ["Water Idol", "Water Totem", "Water Pot", "Miracle Totem", "Dragon Mimic"]},
    {id: 105, stars: "******", text: "Sea King Mega", materials: []},
    {id: 106, stars: "**", text: "Stya", materials: ["Water Nymph", "Water Nymph", "Water Nymph", "Water Spirit", "Mimic"]},
    {id: 107, stars: "***", text: "Snow Blade Stya", materials: ["Water Nymph", "Water Nymph", "Water Spirit", "Water Idol", "Bat Mimic"]},
    {id: 108, stars: "****", text: "Frost Queen Stya", materials: ["Water Nymph", "Water Spirit", "Water Totem", "Water Pot", "Bat Mimic"]},
    {id: 109, stars: "*****", text: "Mother Snow Stya", materials: []},
    {id: 110, stars: "***", text: "Elimo", materials: ["Water Nymph", "Water Nymph", "Water Idol", "Mimic"]},
    {id: 111, stars: "****", text: "Royal Elimo", materials: ["Water Nymph", "Water Idol", "Water Totem", "Mimic", "Bat Mimic"]},
    {id: 112, stars: "*****", text: "Genius Elimo", materials: []},
    {id: 113, stars: "***", text: "Dean", materials: ["Water Nymph", "Water Nymph", "Water Nymph", "Water Idol"]},
    {id: 114, stars: "****", text: "Ice Mage Dean", materials: ["Water Idol", "Water Idol", "Water Totem", "Bat Mimic", "Bat Mimic"]},
    {id: 115, stars: "*****", text: "Ice Wizard Dean", materials: []},
    {id: 116, stars: "**", text: "Wendigo", materials: ["Water Spirit", "Mimic"]},
    {id: 117, stars: "***", text: "Hrungnir", materials: []},
    {id: 118, stars: "**", text: "Black Rose Elize", materials: ["Water Nymph", "Water Spirit"]},
    {id: 119, stars: "***", text: "Frozen Rose Elize", materials: []},
    {id: 120, stars: "***", text: "Water Ghost", materials: ["Fire Ghost", "Earth Ghost", "Thunder Ghost", "Light Ghost", "Metal Ghost"]},
    {id: 121, stars: "****", text: "Water King", materials: []},
    {id: 122, stars: "***", text: "Twin Gem Rickel", materials: ["Water Nymph", "Water Spirit", "Water Spirit", "Water Idol"]},
    {id: 123, stars: "****", text: "Twin Flash Rickel", materials: ["Water Idol", "Water Idol", "Water Totem", "Bat Mimic", "Bat Mimic"]},
    {id: 124, stars: "*****", text: "Twin Shot Rickel", materials: []},
    {id: 125, stars: "****", text: "Brave Knight Karl", materials: ["Water Idol", "Water Idol", "Water Totem", "Water Pot", "Water Pot"]},
    {id: 126, stars: "*****", text: "Ice Warrior Karl", materials: []},
    {id: 127, stars: "****", text: "Eliza", materials: ["Water Totem", "Water Idol", "Water Spirit", "Water Pot", "Dark Pot"]},
    {id: 128, stars: "*****", text: "Snow Sibyl Eliza", materials: []},
    {id: 129, stars: "****", text: "Polar Angel Tiara", materials: ["Water Idol", "Water Idol", "Water Totem", "Water Pot", "Bat Mimic"]},
    {id: 130, stars: "*****", text: "Ice Apostle Tiara", materials: []},
    {id: 131, stars: "****", text: "Hail Bot Reeze", materials: ["Water Nymph", "Water Spirit", "Water Idol", "Water Totem", "Water Pot"]},
    {id: 132, stars: "*****", text: "Hail Mech Reeze", materials: []},
    {id: 133, stars: "***", text: "Maiden Serin", materials: ["Water Spirit", "Water Spirit", "Water Idol", "Water Idol", "Mimic"]},
    {id: 134, stars: "****", text: "Gun Lady Serin", materials: ["Water Spirit", "Water Idol", "Water Idol", "Water Totem", "Bat Mimic"]},
    {id: 135, stars: "*****", text: "Gun Goddess Serin", materials: []},
    {id: 136, stars: "**", text: "Pikeman Lance", materials: ["Earth Nymph"]},
    {id: 137, stars: "***", text: "Vine Pike Lance", materials: ["Earth Spirit", "Earth Idol"]},
    {id: 138, stars: "****", text: "Earth Pike Lance", materials: ["Earth Nymph", "Earth Nymph", "Earth Spirit", "Earth Idol", "Earth Totem"]},
    {id: 139, stars: "*****", text: "Nature God Lance", materials: ["Earth Nymph", "Earth Spirit", "Earth Idol", "Earth Totem", "Miracle Totem"]},
    {id: 140, stars: "******", text: "Holy Earth Lance", materials: []},
    {id: 141, stars: "**", text: "Archer Lario", materials: ["Earth Nymph", "Earth Nymph", "Earth Spirit"]},
    {id: 142, stars: "***", text: "Marksman Lario", materials: ["Earth Nymph", "Earth Nymph", "Earth Spirit", "Earth Idol"]},
    {id: 143, stars: "****", text: "Hawkeye Lario", materials: ["Earth Nymph", "Earth Idol", "Earth Idol", "Earth Totem", "Earth Pot"]},
    {id: 144, stars: "*****", text: "Bow God Lario", materials: []},
    {id: 145, stars: "*", text: "Mossy", materials: ["Earth Nymph"]},
    {id: 146, stars: "**", text: "King Mossy", materials: []},
    {id: 147, stars: "*", text: "Geomancer Claris", materials: ["Earth Nymph"]},
    {id: 148, stars: "**", text: "Time Mage Claris", materials: ["Earth Nymph", "Earth Spirit"]},
    {id: 149, stars: "***", text: "Time Lord Claris", materials: []},
    {id: 150, stars: "*", text: "Mandragora", materials: ["Mimic"]},
    {id: 151, stars: "**", text: "Polevik", materials: []},
    {id: 152, stars: "**", text: "Bandit Zaza", materials: ["Earth Nymph", "Earth Nymph", "Earth Spirit"]},
    {id: 153, stars: "***", text: "Head Bandit Zaza", materials: ["Earth Nymph", "Earth Idol", "Mimic", "Mimic"]},
    {id: 154, stars: "****", text: "Wild Bandit Zaza", materials: []},
    {id: 155, stars: "**", text: "Fairy", materials: ["Earth Nymph", "Mimic", "Mimic"]},
    {id: 156, stars: "***", text: "Titania", materials: []},
    {id: 157, stars: "**", text: "Trent", materials: ["Earth Nymph", "Earth Spirit", "Mimic"]},
    {id: 158, stars: "***", text: "Ent", materials: ["Earth Spirit", "Earth Nymph", "Mimic"]},
    {id: 159, stars: "****", text: "Xipe Totec", materials: []},
    {id: 160, stars: "***", text: "Dryad", materials: ["Earth Spirit", "Earth Spirit", "Earth Spirit", "Bat Mimic"]},
    {id: 161, stars: "****", text: "High Elf", materials: ["Earth Nymph", "Earth Spirit", "Earth Idol", "Earth Totem", "Bat Mimic"]},
    {id: 162, stars: "*****", text: "Lemenara", materials: []},
    {id: 163, stars: "***", text: "Princess Lidith", materials: ["Earth Spirit", "Earth Idol", "Bat Mimic"]},
    {id: 164, stars: "****", text: "Queen Lidith", materials: ["Earth Nymph", "Earth Nymph", "Earth Idol", "Earth Totem", "Earth Pot"]},
    {id: 165, stars: "*****", text: "Empress Lidith", materials: []},
    {id: 166, stars: "***", text: "Great Tree Alneu", materials: ["Earth Idol", "Bat Mimic"]},
    {id: 167, stars: "****", text: "World Tree Altro", materials: ["Earth Nymph", "Earth Spirit", "Earth Totem", "Mimic", "Bat Mimic"]},
    {id: 168, stars: "*****", text: "God Tree Eltri", materials: ["Earth Nymph", "Earth Spirit", "Earth Totem", "Miracle Totem", "Dragon Mimic"]},
    {id: 169, stars: "******", text: "Alpha Tree Altri", materials: []},
    {id: 170, stars: "***", text: "Gunner Douglas", materials: ["Earth Spirit", "Earth Spirit", "Earth Spirit", "Earth Idol"]},
    {id: 171, stars: "****", text: "Gun King Douglas", materials: ["Earth Nymph", "Earth Nymph", "Earth Idol", "Earth Totem", "Bat Mimic"]},
    {id: 172, stars: "*****", text: "Gun God Douglas", materials: ["Miracle Totem", "Earth Totem", "Earth Idol", "Earth Pot", "Dragon Mimic"]},
    {id: 173, stars: "******", text: "Holy Arms Douglas", materials: []},
    {id: 174, stars: "**", text: "Boxer Nemia", materials: ["Earth Nymph", "Earth Nymph", "Earth Nymph", "Earth Spirit", "Mimic"]},
    {id: 175, stars: "***", text: "Brawler Nemia", materials: ["Earth Nymph", "Earth Spirit", "Earth Spirit", "Earth Idol", "Bat Mimic"]},
    {id: 176, stars: "****", text: "Gaia Fist Nemia", materials: ["Earth Nymph", "Earth Spirit", "Earth Totem", "Earth Pot", "Bat Mimic"]},
    {id: 177, stars: "*****", text: "Quake Fist Nemia", materials: []},
    {id: 178, stars: "***", text: "Pixy Leore", materials: ["Earth Nymph", "Earth Nymph", "Earth Idol", "Mimic"]},
    {id: 179, stars: "****", text: "Pixy Royal Leore", materials: ["Earth Nymph", "Earth Idol", "Earth Totem", "Mimic", "Bat Mimic"]},
    {id: 180, stars: "*****", text: "Pixy King Leore", materials: []},
    {id: 181, stars: "***", text: "Edea", materials: ["Earth Nymph", "Earth Nymph", "Earth Spirit", "Earth Idol"]},
    {id: 182, stars: "****", text: "Earth Knight Edea", materials: ["Earth Idol", "Earth Idol", "Earth Totem", "Bat Mimic", "Bat Mimic"]},
    {id: 183, stars: "*****", text: "Mother Earth Edea", materials: []},
    {id: 184, stars: "**", text: "Dwarf", materials: ["Earth Spirit", "Mimic"]},
    {id: 185, stars: "***", text: "Prince Dwarf", materials: []},
    {id: 186, stars: "**", text: "Poet Elton", materials: ["Earth Nymph", "Earth Spirit"]},
    {id: 187, stars: "***", text: "Bard Elton", materials: []},
    {id: 188, stars: "***", text: "Earth Ghost", materials: ["Fire Ghost", "Water Ghost", "Thunder Ghost", "Light Ghost", "Metal Ghost"]},
    {id: 189, stars: "****", text: "Earth King", materials: []},
    {id: 190, stars: "***", text: "Twins Il &amp; Mina", materials: ["Earth Nymph", "Earth Spirit", "Earth Spirit", "Earth Idol"]},
    {id: 191, stars: "****", text: "Earthly Il &amp; Mina", materials: ["Earth Idol", "Earth Idol", "Earth Totem", "Bat Mimic", "Bat Mimic"]},
    {id: 192, stars: "*****", text: "Gemini Il &amp; Mina", materials: []},
    {id: 193, stars: "****", text: "Warrior Lugina", materials: ["Earth Idol", "Earth Idol", "Earth Totem", "Earth Pot", "Earth Pot"]},
    {id: 194, stars: "*****", text: "Gaia King Lugina", materials: []},
    {id: 195, stars: "****", text: "Paula", materials: ["Earth Spirit", "Earth Idol", "Earth Totem", "Earth Pot", "Dark Pot"]},
    {id: 196, stars: "*****", text: "Rose Sibyl Paula", materials: []},
    {id: 197, stars: "****", text: "Scar Blade Zelban", materials: ["Earth Idol", "Earth Idol", "Earth Totem", "Earth Pot", "Bat Mimic"]},
    {id: 198, stars: "*****", text: "Blade Hero Zelban", materials: []},
    {id: 199, stars: "****", text: "Golem", materials: ["Earth Idol", "Earth Idol", "Earth Totem", "Earth Pot", "Earth Pot"]},
    {id: 200, stars: "*****", text: "Great Golem", materials: []},
    {id: 201, stars: "****", text: "Pugilist Dilma", materials: ["Earth Totem", "Earth Idol", "Earth Pot", "Earth Spirit", "Earth Nymph"]},
    {id: 202, stars: "*****", text: "Champ Fist Dilma", materials: []},
    {id: 203, stars: "***", text: "Maiden Bayley", materials: ["Earth Spirit", "Earth Spirit", "Earth Idol", "Earth Idol", "Mimic"]},
    {id: 204, stars: "****", text: "Nyan Slash Bayley", materials: ["Earth Spirit", "Earth Idol", "Earth Idol", "Earth Totem", "Bat Mimic"]},
    {id: 205, stars: "*****", text: "Wild Slash Bayley", materials: []},
    {id: 206, stars: "**", text: "Warrior Eze", materials: ["Thunder Nymph"]},
    {id: 207, stars: "***", text: "Thunder Eze", materials: ["Thunder Spirit", "Thunder Idol"]},
    {id: 208, stars: "****", text: "Thunder King Eze", materials: ["Thunder Nymph", "Thunder Nymph", "Thunder Spirit", "Thunder Idol", "Thunder Totem"]},
    {id: 209, stars: "*****", text: "Thunder God Eze", materials: ["Thunder Nymph", "Thunder Spirit", "Thunder Idol", "Thunder Totem", "Miracle Totem"]},
    {id: 210, stars: "******", text: "Holy Thunder Eze", materials: []},
    {id: 211, stars: "**", text: "Advisor Weiss", materials: ["Thunder Nymph", "Thunder Nymph", "Thunder Spirit"]},
    {id: 212, stars: "***", text: "Strategist Weiss", materials: ["Thunder Nymph", "Thunder Nymph", "Thunder Spirit", "Thunder Idol"]},
    {id: 213, stars: "****", text: "Commander Weiss", materials: ["Thunder Nymph", "Thunder Idol", "Thunder Idol", "Thunder Totem", "Thunder Pot"]},
    {id: 214, stars: "*****", text: "General Weiss", materials: []},
    {id: 215, stars: "*", text: "Sparky", materials: ["Thunder Nymph"]},
    {id: 216, stars: "**", text: "King Sparky", materials: []},
    {id: 217, stars: "*", text: "Dancer May", materials: ["Thunder Nymph"]},
    {id: 218, stars: "**", text: "High Dancer May", materials: ["Thunder Nymph", "Thunder Spirit"]},
    {id: 219, stars: "***", text: "Royal Dancer May", materials: []},
    {id: 220, stars: "*", text: "Harpy", materials: ["Mimic"]},
    {id: 221, stars: "**", text: "Aero", materials: []},
    {id: 222, stars: "**", text: "Sky Pirate Grafl", materials: ["Thunder Nymph", "Thunder Nymph", "Thunder Spirit"]},
    {id: 223, stars: "***", text: "Sky Boss Grafl", materials: ["Thunder Nymph", "Thunder Idol", "Mimic", "Mimic"]},
    {id: 224, stars: "****", text: "Sky Emperor Grafl", materials: []},
    {id: 225, stars: "**", text: "Minotaur", materials: ["Thunder Nymph", "Mimic", "Mimic"]},
    {id: 226, stars: "***", text: "Cyclops", materials: []},
    {id: 227, stars: "**", text: "Sylph", materials: ["Thunder Nymph", "Thunder Spirit", "Mimic"]},
    {id: 228, stars: "***", text: "Djin", materials: ["Thunder Spirit", "Thunder Nymph", "Mimic"]},
    {id: 229, stars: "****", text: "Crow Tengu", materials: []},
    {id: 230, stars: "***", text: "Thunderbird", materials: ["Thunder Spirit", "Thunder Spirit", "Thunder Spirit", "Bat Mimic"]},
    {id: 231, stars: "****", text: "Great Falcon Ziz", materials: ["Thunder Totem", "Thunder Idol", "Thunder Spirit", "Thunder Nymph", "Bat Mimic"]},
    {id: 232, stars: "*****", text: "Zazabis", materials: []},
    {id: 233, stars: "***", text: "Sky Knight Falma", materials: ["Thunder Spirit", "Thunder Idol", "Bat Mimic"]},
    {id: 234, stars: "****", text: "Sky King Falma", materials: ["Thunder Nymph", "Thunder Nymph", "Thunder Idol", "Thunder Totem", "Thunder Pot"]},
    {id: 235, stars: "*****", text: "Sky Legend Falma", materials: []},
    {id: 236, stars: "***", text: "Behemoth", materials: ["Thunder Idol", "Bat Mimic"]},
    {id: 237, stars: "****", text: "King Behemoth", materials: ["Thunder Nymph", "Thunder Spirit", "Thunder Totem", "Mimic", "Bat Mimic"]},
    {id: 238, stars: "*****", text: "Alpha Behemoth", materials: ["Thunder Nymph", "Thunder Spirit", "Thunder Totem", "Miracle Totem", "Dragon Mimic"]},
    {id: 239, stars: "******", text: "Omega Behemoth", materials: []},
    {id: 240, stars: "***", text: "Emilia", materials: ["Thunder Spirit", "Thunder Spirit", "Thunder Spirit", "Thunder Idol"]},
    {id: 241, stars: "****", text: "Princess Emilia", materials: ["Thunder Nymph", "Thunder Nymph", "Thunder Idol", "Thunder Totem", "Bat Mimic"]},
    {id: 242, stars: "*****", text: "Goddess Emilia", materials: ["Thunder Idol", "Thunder Pot", "Thunder Totem", "Miracle Totem", "Dragon Mimic"]},
    {id: 243, stars: "******", text: "Holy Shock Emilia", materials: []},
    {id: 244, stars: "**", text: "Zeln", materials: ["Thunder Nymph", "Thunder Nymph", "Thunder Nymph", "Thunder Spirit", "Mimic"]},
    {id: 245, stars: "***", text: "Spark Kick Zeln", materials: ["Thunder Nymph", "Thunder Nymph", "Thunder Spirit", "Thunder Idol", "Bat Mimic"]},
    {id: 246, stars: "****", text: "Thunder Kick Zeln", materials: ["Thunder Nymph", "Thunder Spirit", "Thunder Totem", "Thunder Pot", "Bat Mimic"]},
    {id: 247, stars: "*****", text: "Thunder Punt Zeln", materials: []},
    {id: 248, stars: "***", text: "Tinkerer Elulu", materials: ["Thunder Nymph", "Thunder Nymph", "Thunder Idol", "Mimic"]},
    {id: 249, stars: "****", text: "Inventor Elulu", materials: ["Thunder Nymph", "Thunder Idol", "Thunder Totem", "Mimic", "Bat Mimic"]},
    {id: 250, stars: "*****", text: "Bolt Mallet Elulu", materials: []},
    {id: 251, stars: "***", text: "Loch", materials: ["Thunder Nymph", "Thunder Nymph", "Thunder Spirit", "Thunder Idol"]},
    {id: 252, stars: "****", text: "Shock Bow Loch", materials: ["Thunder Idol", "Thunder Idol", "Thunder Totem", "Bat Mimic", "Bat Mimic"]},
    {id: 253, stars: "*****", text: "Zeus Bow Loch", materials: []},
    {id: 254, stars: "**", text: "Empusa", materials: ["Thunder Spirit", "Mimic"]},
    {id: 255, stars: "***", text: "Gorgon", materials: []},
    {id: 256, stars: "**", text: "Wild Cat Parmi", materials: ["Thunder Nymph", "Thunder Spirit"]},
    {id: 257, stars: "***", text: "Thunder Cat Parmi", materials: []},
    {id: 258, stars: "***", text: "Thunder Ghost", materials: ["Fire Ghost", "Water Ghost", "Earth Ghost", "Light Ghost", "Metal Ghost"]},
    {id: 259, stars: "****", text: "Thunder King", materials: []},
    {id: 260, stars: "***", text: "Bolt Pike Amy", materials: ["Thunder Nymph", "Thunder Spirit", "Thunder Spirit", "Thunder Idol"]},
    {id: 261, stars: "****", text: "Bolt Knight Amy", materials: ["Thunder Idol", "Thunder Idol", "Thunder Totem", "Bat Mimic", "Bat Mimic"]},
    {id: 262, stars: "*****", text: "Bolt Goddess Amy", materials: []},
    {id: 263, stars: "****", text: "Paladin Paris", materials: ["Thunder Totem", "Thunder Idol", "Thunder Idol", "TBA", "TBA"]},
    {id: 264, stars: "*****", text: "Royal Guard Paris", materials: []},
    {id: 265, stars: "****", text: "Zele", materials: ["Thunder Totem", "Thunder Idol", "Thunder Spirit", "Thunder Pot", "Light Pot"]},
    {id: 266, stars: "*****", text: "Bolt Sibyl Zele", materials: []},
    {id: 267, stars: "****", text: "Drakeborn Lodin", materials: ["Thunder Idol", "Thunder Idol", "Thunder Totem", "Thunder Pot", "Bat Mimic"]},
    {id: 268, stars: "*****", text: "Drake God Lodin", materials: []},
    {id: 269, stars: "****", text: "Sky Angel Kushra", materials: ["Thunder Totem", "Thunder Idol", "Thunder Idol", "Thunder Pot", "Thunder Pot"]},
    {id: 270, stars: "*****", text: "Rebel Angel Elsel", materials: []},
    {id: 271, stars: "****", text: "Shock Mage Rashil", materials: ["Thunder Nymph", "Thunder Spirit", "Thunder Idol", "Thunder Totem", "Thunder Pot"]},
    {id: 272, stars: "*****", text: "Bolt Magus Rashil", materials: []},
    {id: 273, stars: "***", text: "Maiden Fennia", materials: ["Thunder Spirit", "Thunder Spirit", "Thunder Idol", "Thunder Idol", "Mimic"]},
    {id: 274, stars: "****", text: "Raid Bomb Fennia", materials: ["Thunder Spirit", "Thunder Idol", "Thunder Idol", "Thunder Totem", "Bat Mimic"]},
    {id: 275, stars: "*****", text: "Raid Bolt Fennia", materials: []},
    {id: 276, stars: "**", text: "Squire Atro", materials: ["Light Nymph"]},
    {id: 277, stars: "***", text: "Knight Atro", materials: ["Light Spirit", "Light Idol"]},
    {id: 278, stars: "****", text: "Holy Knight Atro", materials: ["Light Nymph", "Light Nymph", "Light Spirit", "Light Idol", "Light Totem"]},
    {id: 279, stars: "*****", text: "God Atro", materials: ["Light Nymph", "Light Spirit", "Light Idol", "Light Totem", "Miracle Totem"]},
    {id: 280, stars: "******", text: "Holy Light Atro", materials: []},
    {id: 281, stars: "**", text: "Luna", materials: ["Light Nymph", "Light Nymph", "Light Spirit"]},
    {id: 282, stars: "***", text: "Sunshine Luna", materials: ["Light Nymph", "Light Nymph", "Light Spirit", "Light Idol"]},
    {id: 283, stars: "****", text: "Holy Queen Luna", materials: ["Light Nymph", "Light Idol", "Light Idol", "Light Totem", "Light Pot"]},
    {id: 284, stars: "*****", text: "Holy Empress Luna", materials: []},
    {id: 285, stars: "*", text: "Glowy", materials: ["Light Nymph"]},
    {id: 286, stars: "**", text: "King Glowy", materials: []},
    {id: 287, stars: "*", text: "Sage Mimir", materials: ["Light Nymph"]},
    {id: 288, stars: "**", text: "Light Lord Mimir", materials: ["Light Nymph", "Light Spirit"]},
    {id: 289, stars: "***", text: "Great Sage Mimir", materials: []},
    {id: 290, stars: "*", text: "Angel", materials: ["Mimic"]},
    {id: 291, stars: "**", text: "Archangel", materials: []},
    {id: 292, stars: "**", text: "Unicorn", materials: ["Light Nymph", "Mimic", "Mimic"]},
    {id: 293, stars: "***", text: "Pegasus", materials: []},
    {id: 294, stars: "**", text: "Priestess Maria", materials: ["Light Nymph", "Light Spirit", "Mimic"]},
    {id: 295, stars: "***", text: "Angel Maria", materials: ["Light Idol", "Light Spirit", "Light Nymph", "Mimic"]},
    {id: 296, stars: "****", text: "Saint Maria", materials: []},
    {id: 297, stars: "***", text: "Valkyrie", materials: ["Light Spirit", "Light Spirit", "Light Spirit", "Bat Mimic"]},
    {id: 298, stars: "****", text: "Sky Hero Athena", materials: ["Light Totem", "Light Idol", "Light Spirit", "Light Nymph", "Bat Mimic"]},
    {id: 299, stars: "*****", text: "Legendary Jona", materials: []},
    {id: 300, stars: "***", text: "Cowboy Heidt", materials: ["Light Spirit", "Light Idol", "Bat Mimic"]},
    {id: 301, stars: "****", text: "Holy Shot Heidt", materials: ["Light Nymph", "Light Nymph", "Light Idol", "Light Totem", "Light Pot"]},
    {id: 302, stars: "*****", text: "Pistol God Heidt", materials: []},
    {id: 303, stars: "***", text: "Wyvern", materials: ["Light Idol", "Bat Mimic"]},
    {id: 304, stars: "****", text: "Bahamut", materials: ["Light Nymph", "Light Spirit", "Light Totem", "Mimic", "Bat Mimic"]},
    {id: 305, stars: "*****", text: "Rameldria", materials: ["Light Nymph", "Light Spirit", "Light Totem", "Miracle Totem", "Dragon Mimic"]},
    {id: 306, stars: "******", text: "Duelmex", materials: []},
    {id: 307, stars: "***", text: "Knight Will", materials: ["Light Spirit", "Light Spirit", "Light Spirit", "Light Idol"]},
    {id: 308, stars: "****", text: "Holy Knight Will", materials: ["Light Nymph", "Light Nymph", "Light Idol", "Light Totem", "Bat Mimic"]},
    {id: 309, stars: "*****", text: "God Knight Will", materials: ["Light Idol", "Light Totem", "Dragon Mimic", "Light Pot", "Miracle Totem"]},
    {id: 310, stars: "******", text: "Holy Guard Will", materials: []},
    {id: 311, stars: "**", text: "Traveler Alma", materials: ["Light Nymph", "Light Nymph", "Light Nymph", "Light Spirit", "Mimic"]},
    {id: 312, stars: "***", text: "Adventurer Alma", materials: ["Light Nymph", "Light Nymph", "Light Spirit", "Light Idol", "Bat Mimic"]},
    {id: 313, stars: "****", text: "Hero Alma", materials: ["Light Nymph", "Light Spirit", "Light Totem", "Light Pot", "Hero Alma"]},
    {id: 314, stars: "*****", text: "Brave Hero Alma", materials: []},
    {id: 315, stars: "***", text: "Knight Aem", materials: ["Light Nymph", "Light Nymph", "Light Idol", "Mimic"]},
    {id: 316, stars: "****", text: "Champion Aem", materials: ["Light Nymph", "Light Idol", "Light Totem", "Mimic", "Bat Mimic"]},
    {id: 317, stars: "*****", text: "Holy Master Aem", materials: []},
    {id: 318, stars: "***", text: "Eight Blade Sefia", materials: ["Light Nymph", "Light Spirit", "Light Spirit", "Light Idol"]},
    {id: 319, stars: "****", text: "Blade Storm Sefia", materials: ["Light Idol", "Light Idol", "Light Totem", "Bat Mimic", "Bat Mimic"]},
    {id: 320, stars: "*****", text: "Blade Queen Sefia", materials: []},
    {id: 321, stars: "**", text: "Al-mi'raj", materials: ["Light Spirit", "Mimic"]},
    {id: 322, stars: "***", text: "Cait Sith", materials: []},
    {id: 323, stars: "**", text: "Shrine Girl Amul", materials: ["Light Nymph", "Light Spirit"]},
    {id: 324, stars: "***", text: "Holy Maiden Amul", materials: []},
    {id: 325, stars: "***", text: "Light Ghost", materials: ["Fire Ghost", "Water Ghost", "Earth Ghost", "Thunder Ghost", "Metal Ghost"]},
    {id: 326, stars: "****", text: "Light King", materials: []},
    {id: 327, stars: "****", text: "Sola", materials: ["Light Totem", "Light Idol", "Light Spirit", "Fire Pot", "Thunder Pot"]},
    {id: 328, stars: "*****", text: "Ray Sibyl Sola", materials: []},
    {id: 329, stars: "****", text: "Legionary Melchio", materials: ["Light Idol", "Light Idol", "Light Totem", "Light Pot", "Bat Mimic"]},
    {id: 330, stars: "*****", text: "Centurion Melchio", materials: []},
    {id: 331, stars: "****", text: "White Lebra", materials: ["Light Totem", "Light Idol", "Light Idol", "Light Pot", "Light Pot"]},
    {id: 332, stars: "*****", text: "Lubradine", materials: []},
    {id: 333, stars: "****", text: "Cyborg Lilith", materials: ["Light Nymph", "Light Spirit", "Light Idol", "Light Totem", "Light Pot"]},
    {id: 334, stars: "*****", text: "Cyborg Lilith II", materials: []},
    {id: 335, stars: "***", text: "Maiden Vanila", materials: ["Light Spirit", "Light Spirit", "Light Idol", "Light Idol", "Mimic"]},
    {id: 336, stars: "****", text: "Sky Queen Vanila", materials: ["Light Spirit", "Light Idol", "Light Idol", "Light Totem", "Bat Mimic"]},
    {id: 337, stars: "*****", text: "Sky Angel Vanila", materials: []},
    {id: 338, stars: "**", text: "Iron Magress", materials: ["Dark Nymph"]},
    {id: 339, stars: "***", text: "Heavy Magress", materials: ["Dark Spirit", "Dark Idol"]},
    {id: 340, stars: "****", text: "Black Magress", materials: ["Dark Nymph", "Dark Nymph", "Dark Spirit", "Dark Idol", "Dark Totem"]},
    {id: 341, stars: "*****", text: "Death Magress", materials: ["Dark Nymph", "Dark Spirit", "Dark Idol", "Dark Totem", "Miracle Totem"]},
    {id: 342, stars: "******", text: "Unholy Magress", materials: []},
    {id: 343, stars: "**", text: "Mifune", materials: ["Dark Nymph", "Dark Nymph", "Dark Spirit"]},
    {id: 344, stars: "***", text: "Samurai Mifune", materials: ["Dark Nymph", "Dark Nymph", "Dark Spirit", "Dark Idol"]},
    {id: 345, stars: "****", text: "God Blade Mifune", materials: ["Dark Nymph", "Dark Idol", "Dark Idol", "Dark Totem", "Dark Pot"]},
    {id: 346, stars: "*****", text: "Ryujin Mifune", materials: []},
    {id: 347, stars: "*", text: "Gloomy", materials: ["Dark Nymph"]},
    {id: 348, stars: "**", text: "King Gloomy", materials: []},
    {id: 349, stars: "*", text: "Sorceress Lily", materials: ["Dark Nymph"]},
    {id: 350, stars: "**", text: "Magician Lily", materials: ["Dark Nymph", "Dark Spirit"]},
    {id: 351, stars: "***", text: "Dark Arts Lily", materials: []},
    {id: 352, stars: "*", text: "Skeleton", materials: ["Mimic"]},
    {id: 353, stars: "**", text: "Skeleton King", materials: []},
    {id: 354, stars: "**", text: "Medusa", materials: ["Dark Nymph", "Mimic", "Mimic"]},
    {id: 355, stars: "***", text: "Zahhak", materials: []},
    {id: 356, stars: "**", text: "Lilin", materials: ["Dark Nymph", "Dark Spirit", "Mimic"]},
    {id: 357, stars: "***", text: "Succubus", materials: ["Dark Idol", "Dark Spirit", "Dark Nymph", "Mimic"]},
    {id: 358, stars: "****", text: "Nyx", materials: []},
    {id: 359, stars: "***", text: "Vampire", materials: ["Dark Spirit", "Dark Spirit", "Dark Spirit", "Bat Mimic"]},
    {id: 360, stars: "****", text: "Lich", materials: ["Dark Totem", "Dark Idol", "Dark Spirit", "Dark Nymph", "Bat Mimic"]},
    {id: 361, stars: "*****", text: "Legion", materials: []},
    {id: 362, stars: "***", text: "Shida", materials: ["Dark Spirit", "Dark Idol", "Bat Mimic"]},
    {id: 363, stars: "****", text: "Garroter Shida", materials: ["Dark Nymph", "Dark Nymph", "Dark Idol", "Dark Totem", "Dark Pot"]},
    {id: 364, stars: "*****", text: "Executioner Shida", materials: []},
    {id: 365, stars: "***", text: "Memetes", materials: ["Dark Idol", "Bat Mimic"]},
    {id: 366, stars: "****", text: "Hell King Hades", materials: ["Dark Nymph", "Dark Spirit", "Dark Totem", "Mimic", "Bat Mimic"]},
    {id: 367, stars: "*****", text: "Death God Lodaga", materials: ["Dark Nymph", "Dark Spirit", "Dark Totem", "Miracle Totem", "Dragon Mimic"]},
    {id: 368, stars: "******", text: "Hellborn Dilias", materials: []},
    {id: 369, stars: "***", text: "Alice", materials: ["Dark Spirit", "Dark Spirit", "Dark Spirit", "Dark Idol"]},
    {id: 370, stars: "****", text: "Scythe Alice", materials: ["Dark Nymph", "Dark Nymph", "Dark Idol", "Dark Totem", "Bat Mimic"]},
    {id: 371, stars: "*****", text: "Scythe God Alice", materials: ["Dark Pot", "Dark Idol", "Dragon Mimic", "Dark Totem", "Miracle Totem"]},
    {id: 372, stars: "******", text: "Hell Keep Alice", materials: []},
    {id: 373, stars: "***", text: "Metal Ghost", materials: ["Water Ghost", "Fire Ghost", "Earth Ghost", "Thunder Ghost", "Light Ghost"]},
    {id: 374, stars: "****", text: "Metal King", materials: []},
    {id: 375, stars: "**", text: "Ninja Oboro", materials: ["Dark Nymph", "Dark Nymph", "Dark Nymph", "Dark Spirit", "Mimic"]},
    {id: 376, stars: "***", text: "Assassin Oboro", materials: ["Dark Nymph", "Dark Nymph", "Dark Spirit", "Dark Idol", "Bat Mimic"]},
    {id: 377, stars: "****", text: "Shadow Oboro", materials: ["Dark Nymph", "Dark Spirit", "Dark Totem", "Dark Pot", "Bat Mimic"]},
    {id: 378, stars: "*****", text: "Red Shadow Oboro", materials: []},
    {id: 379, stars: "***", text: "Lemia", materials: ["Dark Nymph", "Dark Nymph", "Dark Idol", "Mimic"]},
    {id: 380, stars: "****", text: "Necromancer Lemia", materials: ["Dark Nymph", "Dark Idol", "Dark Totem", "Mimic", "Bat Mimic"]},
    {id: 381, stars: "*****", text: "Soul Keeper Lemia", materials: []},
    {id: 382, stars: "***", text: "Kikuri", materials: ["Dark Nymph", "Dark Spirit", "Dark Spirit", "Dark Idol"]},
    {id: 383, stars: "****", text: "Goth Kikuri", materials: ["Dark Spirit", "Dark Idol", "Dark Totem", "Bat Mimic", "Bat Mimic"]},
    {id: 384, stars: "*****", text: "Goth Idol Kikuri", materials: []},
    {id: 385, stars: "**", text: "Imp", materials: ["Dark Spirit", "Mimic"]},
    {id: 386, stars: "***", text: "Incubus", materials: []},
    {id: 387, stars: "**", text: "Gambler Zeul", materials: ["Dark Nymph", "Dark Spirit"]},
    {id: 388, stars: "***", text: "High Roller Zeul", materials: []},
    {id: 389, stars: "****", text: "Disciple Zebra", materials: ["Dark Idol", "Dark Idol", "Dark Totem", "Dark Pot", "Dark Pot"]},
    {id: 390, stars: "*****", text: "Mad God Zebra", materials: []},
    {id: 391, stars: "****", text: "Madia", materials: ["Dark Totem", "Dark Idol", "Dark Spirit", "Water Pot", "Earth Pot"]},
    {id: 392, stars: "*****", text: "Night Sibyl Madia", materials: []},
    {id: 393, stars: "****", text: "Duel-GX", materials: ["Dark Idol", "Dark Idol", "Dark Totem", "Dark Pot", "Bat Mimic"]},
    {id: 394, stars: "*****", text: "Duel-GX II", materials: []},
    {id: 395, stars: "****", text: "Dark Swords Logan", materials: ["Dark Nymph", "Dark Spirit", "Dark Idol", "Dark Totem", "Dark Pot"]},
    {id: 396, stars: "*****", text: "Evil Blades Logan", materials: []},
    {id: 397, stars: "***", text: "Maiden Lico", materials: ["Dark Spirit", "Dark Spirit", "Dark Idol", "Dark Idol", "Mimic"]},
    {id: 398, stars: "****", text: "Dark Blade Lico", materials: ["Dark Idol", "Dark Idol", "Dark Totem", "Bat Mimic", "Bat Mimic"]},
    {id: 399, stars: "*****", text: "Demon Blade Lico", materials: []},
    {id: 400, stars: "***", text: "Xenon", materials: ["Dark Idol", "Dark Spirit", "Dark Nymph", "Dark Pot", "Mimic"]},
    {id: 401, stars: "****", text: "Royal Guard Xenon", materials: []}
  ];

  var unitInventory = [];
  var evoMats = [];

  $('#search-unit').select2({
    data: units
  }).on('change', function(selectedObject) {
    unitInventory.push(selectedObject.added);
    evoMats.push(selectedObject.added.materials);

    // console.log(unitInventory);
    render();
  });


  function render() {
    tableBody = $('#unit-list tbody');
    tableBody.html('');

    $.each(unitInventory, function(index, unit) {
      tableRow = "<tr><td>" + unit.text + "</td><td>" + unit.materials + "</td></tr>";
      tableBody.append(tableRow);
    });

    renderTotalEvoMatCounts();
  }

  var totalEvoMats = {};

  function countEvoMats() {
    // flatten the array
    evoMats = [].concat.apply([], evoMats);

    for(i = 0; i < evoMats.length; ++i) {
      if(!totalEvoMats[evoMats[i]])
        totalEvoMats[evoMats[i]] = 0;
      ++totalEvoMats[evoMats[i]];
    }
  }

  function renderTotalEvoMatCounts() {
    countEvoMats();
    tableBody = $('#total-evo-counts tbody');
    tableBody.html('');

    for(key in totalEvoMats) {
      console.log(key);
      tableRow = "<tr><td>" + key + "</td><td>" + totalEvoMats[key] + "</td></tr>";
      tableBody.append(tableRow);
    }
  }
});
